from typing import TYPE_CHECKING, Callable, Concatenate, overload
from celery import shared_task as _st

class TaskResult[**P, R]:
    def get(self) -> R: ...

class SharedTask[**P, R]:
    def __init__(self, func: Callable[P, R]) -> None: ...
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R: ...
    def delay(self, *args: P.args, **kwargs: P.kwargs) -> TaskResult[P, R]: ...
    def bind(self, func: "Callable[[SharedTask[P, R]], SharedTask[P, R]]") -> "SharedTask[P, R]": ...

@overload
def shared_task_helper[T,**P, R](func: Callable[P, R], bind: bool = False) -> SharedTask[P, R]: ...
@overload
def shared_task_helper[T,**P, R](func=None, bind: bool = True) -> Callable[[Callable[Concatenate[T,P], R]], SharedTask[P, R]]: ...
def shared_task_helper[T,**P, R](func: Callable[P, R] | None = None, bind: bool = False) -> SharedTask[P, R] | Callable[[Callable[P, R]], SharedTask[P, R]]: ...

if TYPE_CHECKING:
    shared_task = shared_task_helper
else:
    shared_task = _st
