"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv

load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect MinIO usage first (some deployments prefer MinIO)
USE_MINIO = os.getenv("USE_MINIO") == "True" or bool(
    os.getenv("MINIO_ENDPOINT") or os.getenv("MINIO_URL") or os.getenv("MINIO_BUCKET")
)

# Determine whether to use S3/MinIO for media storage. Set via env vars like
# AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_STORAGE_BUCKET_NAME or
# helper flags USE_S3=True or USE_MINIO=True
USE_S3 = bool(
    os.getenv("USE_S3") == "True"
    or os.getenv("AWS_STORAGE_BUCKET_NAME")
    or os.getenv("AWS_S3_BUCKET")
    or USE_MINIO
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "storages",
    "users",
    "feeds",
    "ninja",
    "django_celery_results",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serve static files with WhiteNoise when running under ASGI (uvicorn)
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "base.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "base.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DATABASE_NAME"),
        "USER": os.getenv("DATABASE_USER"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),
        "HOST": os.getenv("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT"),
        "TEST": {
            "MIRROR": "default",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Serve static files at /static/ and collect to STATIC_ROOT
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# Media files (cached images)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN", None)


# MinIO-only configuration

# Use the canonical Django setting name so other code can import it

STORAGES = {"default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"}}
# Ensure staticfiles storage is defined (helps system checks during tests)
STORAGES.setdefault(
    "staticfiles", {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"}
)

AWS_ACCESS_KEY_ID = os.getenv("MINIO_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("MINIO_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("MINIO_BUCKET")
AWS_S3_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT")
AWS_S3_SIGNATURE_VERSION = os.getenv("MINIO_SIGNATURE_VERSION", "s3v4")
AWS_S3_VERIFY = os.getenv("MINIO_USE_SSL", "True") == "True"

# Construct MEDIA_URL using MinIO endpoint and bucket
if AWS_S3_ENDPOINT_URL and AWS_STORAGE_BUCKET_NAME:
    endpoint = AWS_S3_ENDPOINT_URL.rstrip("/")
    MEDIA_URL = f"{endpoint}/{AWS_STORAGE_BUCKET_NAME}/"

AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": os.getenv("AWS_S3_CACHE_CONTROL", "max-age=86400"),
}

# Use WhiteNoise's storage backend for compressed static files. This is
# compatible with serving static files directly from the Django process
# (e.g., when using uvicorn + WhiteNoise). In production you may prefer
# serving from S3/MinIO and override this.
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "users.User"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Celery Task Routes - 큐별로 작업 분리
CELERY_TASK_ROUTES = {
    # 큐 1: feed_main - 메인 URL 크롤링 및 디테일 분배 (chord로 큐2 기다림)
    "feeds.tasks.update_feed_items": {"queue": "feed_main"},
    "feeds.tasks.update_all_feeds": {"queue": "feed_main"},
    "feeds.tasks.update_feeds_by_category": {"queue": "feed_main"},
    "feeds.tasks.crawl_rss_everything_source": {"queue": "feed_main"},
    # 큐 2: detail_worker - 개별 디테일 페이지 크롤링 후 이미지 캐시 요청 (기다리지 않음)
    "feeds.tasks.crawl_detail_page": {"queue": "detail_worker"},
    "feeds.tasks.collect_detail_results": {"queue": "detail_worker"},
    # 큐 3: image_aggregate - 이미지 URL 추출 및 사이즈별 분배
    "feeds.tasks.precache_images_for_item": {"queue": "image_aggregate"},
    # 큐 4: image_worker - 실제 Next.js 이미지 캐시
    "feeds.tasks.cache_single_image": {"queue": "image_worker"},
}

# Default queue for tasks without explicit routing
CELERY_TASK_DEFAULT_QUEUE = "celery"

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Session and CSRF cookie settings for cross-origin / Docker scenarios
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
# Allow cookies over HTTP in development (set to True in production with HTTPS)
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Cache configuration - prefer explicit REDIS_CACHE_URL, fallback to broker URL
# Cache configuration removed (image caching feature removed). Use Django's default cache.
APPEND_SLASH = False
