# Generated by Django 5.2.9 on 2025-12-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, help_text='Celery Task ID', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('items_found', models.IntegerField(default=0, help_text='발견된 총 아이템 수')),
                ('items_created', models.IntegerField(default=0, help_text='새로 생성된 아이템 수')),
                ('error_message', models.TextField(blank=True, help_text='에러 메시지 (실패 시)')),
                ('started_at', models.DateTimeField(blank=True, help_text='Task 시작 시간', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Task 완료 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RSSEverythingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('rss', 'RSS/Atom (Classic)'), ('page_scraping', 'Page Scraping'), ('detail_page_scraping', 'Detail Page Scraping')], default='rss', help_text='소스 타입 (RSS/Atom, 페이지 스크래핑, 상세 페이지 스크래핑)', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='이 소스의 활성화 여부')),
                ('url', models.URLField(help_text='RSS URL 또는 크롤링할 페이지 URL')),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('item_selector', models.CharField(blank=True, help_text='아이템 목록의 CSS 셀렉터 (예: article.post, .news-item)', max_length=500)),
                ('title_selector', models.CharField(blank=True, help_text='제목 CSS 셀렉터 (아이템 내부)', max_length=500)),
                ('link_selector', models.CharField(blank=True, help_text='링크 CSS 셀렉터 (아이템 내부, 비워두면 title_selector의 a 태그 사용)', max_length=500)),
                ('description_selector', models.CharField(blank=True, help_text='설명 CSS 셀렉터 (아이템 내부)', max_length=500)),
                ('date_selector', models.CharField(blank=True, help_text='날짜 CSS 셀렉터 (아이템 내부)', max_length=500)),
                ('image_selector', models.CharField(blank=True, help_text='이미지 CSS 셀렉터 (아이템 내부)', max_length=500)),
                ('detail_title_selector', models.CharField(blank=True, help_text='상세 페이지에서 제목 CSS 셀렉터', max_length=500)),
                ('detail_description_selector', models.CharField(blank=True, help_text='상세 페이지에서 설명/요약 CSS 셀렉터', max_length=500)),
                ('detail_content_selector', models.CharField(blank=True, help_text='상세 페이지에서 본문 CSS 셀렉터', max_length=500)),
                ('detail_date_selector', models.CharField(blank=True, help_text='상세 페이지에서 날짜 CSS 셀렉터', max_length=500)),
                ('detail_image_selector', models.CharField(blank=True, help_text='상세 페이지에서 이미지 CSS 셀렉터', max_length=500)),
                ('exclude_selectors', models.JSONField(blank=True, default=list, help_text='제외할 CSS 셀렉터 목록 (예: [".ads", ".sidebar", "script"])')),
                ('date_formats', models.JSONField(blank=True, default=list, help_text='날짜 포맷 목록 (예: ["%Y-%m-%d", "%Y.%m.%d %H:%M"])')),
                ('date_locale', models.CharField(default='ko_KR', help_text='날짜 로케일 (예: ko_KR, en_US)', max_length=20)),
                ('use_browser', models.BooleanField(default=False, help_text='브라우저 렌더링 사용 여부 (JavaScript 필요 시)')),
                ('wait_selector', models.CharField(blank=True, help_text='페이지 로드 완료 확인용 셀렉터', max_length=500)),
                ('timeout', models.IntegerField(default=30000, help_text='타임아웃 (밀리초)')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSS Everything Source',
                'verbose_name_plural': 'RSS Everything Sources',
            },
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('favicon_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('refresh_interval', models.IntegerField(default=60, help_text='자동 새로고침 주기 (분)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('guid', models.CharField(max_length=500, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
