# Generated by Django 5.2.9 on 2025-12-17 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rsscategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.rsscategory'),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsseverythingsource',
            name='feed',
            field=models.ForeignKey(help_text='연결된 RSS 피드', on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='feeds.rssfeed'),
        ),
        migrations.AddField(
            model_name='feedtaskresult',
            name='feed',
            field=models.ForeignKey(help_text='관련 피드', on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='feeds.rssfeed'),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.rssfeed'),
        ),
        migrations.AddIndex(
            model_name='rsscategory',
            index=models.Index(fields=['user'], name='feeds_rssca_user_id_3f953e_idx'),
        ),
        migrations.AddIndex(
            model_name='rsscategory',
            index=models.Index(fields=['user', 'visible'], name='feeds_rssca_user_id_6af167_idx'),
        ),
        migrations.AddIndex(
            model_name='rsscategory',
            index=models.Index(fields=['user', 'order'], name='feeds_rssca_user_id_535f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['user'], name='feeds_rssfe_user_id_956448_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['category'], name='feeds_rssfe_categor_77bb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['user', 'visible'], name='feeds_rssfe_user_id_f6b6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['category', 'visible'], name='feeds_rssfe_categor_3093dc_idx'),
        ),
        migrations.AddIndex(
            model_name='rsseverythingsource',
            index=models.Index(fields=['feed'], name='feeds_rssev_feed_id_d17aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='rsseverythingsource',
            index=models.Index(fields=['feed', 'source_type'], name='feeds_rssev_feed_id_3edcd2_idx'),
        ),
        migrations.AddIndex(
            model_name='rsseverythingsource',
            index=models.Index(fields=['feed', 'is_active'], name='feeds_rssev_feed_id_094ada_idx'),
        ),
        migrations.AddIndex(
            model_name='feedtaskresult',
            index=models.Index(fields=['feed'], name='feeds_feedt_feed_id_1665a2_idx'),
        ),
        migrations.AddIndex(
            model_name='feedtaskresult',
            index=models.Index(fields=['feed', '-created_at'], name='feeds_feedt_feed_id_d759a1_idx'),
        ),
        migrations.AddIndex(
            model_name='feedtaskresult',
            index=models.Index(fields=['status'], name='feeds_feedt_status_0e8d63_idx'),
        ),
        migrations.AddIndex(
            model_name='feedtaskresult',
            index=models.Index(fields=['task_id'], name='feeds_feedt_task_id_e222af_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['feed'], name='feeds_rssit_feed_id_1cc5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['feed', 'is_read'], name='feeds_rssit_feed_id_a6659a_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['feed', 'is_favorite'], name='feeds_rssit_feed_id_39d40e_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['published_at'], name='feeds_rssit_publish_5b7588_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['feed', '-published_at'], name='feeds_rssit_feed_id_2f09db_idx'),
        ),
    ]
