# Generated by Django 6.0 on 2025-12-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='refresh_interval',
            field=models.IntegerField(default=60, help_text='자동 새로고침 주기 (분)'),
        ),
    ]
