# Generated by Django 5.2.9 on 2025-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rssitem',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
