# Generated by Django 6.0 on 2025-12-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_rssfeed_custom_headers_rssfeed_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='favicon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
