# Generated by Django 5.2.9 on 2025-12-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_extend_title_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='author',
            field=models.CharField(blank=True, help_text='아이템 작성자', max_length=255),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text="카테고리 목록 (예: ['Tech', 'News'])"),
        ),
    ]
