# Generated by Django 5.2.9 on 2025-12-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_add_author_categories_to_rssitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsseverythingsource',
            name='author_selector',
            field=models.CharField(blank=True, help_text='작성자 CSS 셀렉터 (아이템 내부)', max_length=500),
        ),
        migrations.AddField(
            model_name='rsseverythingsource',
            name='categories_selector',
            field=models.CharField(blank=True, help_text='카테고리 CSS 셀렉터 (아이템 내부, 여러 개 선택 가능)', max_length=500),
        ),
        migrations.AddField(
            model_name='rsseverythingsource',
            name='detail_author_selector',
            field=models.CharField(blank=True, help_text='상세 페이지에서 작성자 CSS 셀렉터', max_length=500),
        ),
        migrations.AddField(
            model_name='rsseverythingsource',
            name='detail_categories_selector',
            field=models.CharField(blank=True, help_text='상세 페이지에서 카테고리 CSS 셀렉터', max_length=500),
        ),
    ]
