# Generated by Django 5.2.9 on 2025-12-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_cachedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsscategory',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
