# Generated by Django 5.2.9 on 2025-12-15 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_add_category_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cachedimage',
            index=models.Index(fields=['original_url'], name='feeds_cache_origina_2f3b22_idx'),
        ),
        migrations.AddIndex(
            model_name='rsscategory',
            index=models.Index(fields=['user'], name='feeds_rssca_user_id_3f953e_idx'),
        ),
        migrations.AddIndex(
            model_name='rsscategory',
            index=models.Index(fields=['user', 'visible'], name='feeds_rssca_user_id_6af167_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['user'], name='feeds_rssfe_user_id_956448_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['category'], name='feeds_rssfe_categor_77bb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['user', 'visible'], name='feeds_rssfe_user_id_f6b6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['category', 'visible'], name='feeds_rssfe_categor_3093dc_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['feed'], name='feeds_rssit_feed_id_1cc5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['feed', 'is_read'], name='feeds_rssit_feed_id_a6659a_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['feed', 'is_favorite'], name='feeds_rssit_feed_id_39d40e_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['published_at'], name='feeds_rssit_publish_5b7588_idx'),
        ),
        migrations.AddIndex(
            model_name='rssitem',
            index=models.Index(fields=['feed', '-published_at'], name='feeds_rssit_feed_id_2f09db_idx'),
        ),
    ]
