# Generated by Django 5.2.9 on 2025-12-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_add_author_categories_selectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='image',
            field=models.URLField(blank=True, help_text='아이템 이미지 URL'),
        ),
    ]
