# Generated by Django 5.2.9 on 2025-12-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_add_model_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
