# Generated by Django 5.2.9 on 2025-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_rssitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssitem',
            name='image',
            field=models.URLField(blank=True, default='', help_text='아이템 이미지 URL'),
        ),
    ]
