# Generated by Django 5.2.9 on 2025-12-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_add_default_to_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsscategory',
            name='is_public',
            field=models.BooleanField(default=False, help_text='RSS 피드 공개 여부'),
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='is_public',
            field=models.BooleanField(default=False, help_text='RSS 피드 공개 여부'),
        ),
    ]
