# Generated by Django 5.2.9 on 2025-12-16 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_add_cachedimage_dimensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsscategory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='rsscategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='rsscategory',
            index=models.Index(fields=['user', 'order'], name='feeds_rssca_user_id_535f1d_idx'),
        ),
    ]
