# Generated by Django 5.2.9 on 2025-12-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_add_is_public_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeedWithCount',
            fields=[
            ],
            options={
                'verbose_name': 'RSS Feed with Count',
                'verbose_name_plural': 'RSS Feeds with Count',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feeds.rssfeed',),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='favicon_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
