# Generated by Django 5.2.9 on 2025-12-17 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_add_category_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSEverythingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='소스 이름', max_length=200)),
                ('url', models.URLField(help_text='크롤링할 페이지 URL')),
                ('favicon_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('item_selector', models.CharField(help_text='아이템 목록의 CSS 셀렉터 (예: article.post, .news-item)', max_length=500)),
                ('title_selector', models.CharField(help_text='제목 CSS 셀렉터 (아이템 내부)', max_length=500)),
                ('link_selector', models.CharField(blank=True, help_text='링크 CSS 셀렉터 (아이템 내부, 비워두면 title_selector의 a 태그 사용)', max_length=500)),
                ('description_selector', models.CharField(blank=True, help_text='설명 CSS 셀렉터 (아이템 내부)', max_length=500)),
                ('date_selector', models.CharField(blank=True, help_text='날짜 CSS 셀렉터 (아이템 내부)', max_length=500)),
                ('image_selector', models.CharField(blank=True, help_text='이미지 CSS 셀렉터 (아이템 내부)', max_length=500)),
                ('follow_links', models.BooleanField(default=False, help_text='각 아이템의 링크를 따라가서 상세 내용을 가져올지 여부')),
                ('detail_content_selector', models.CharField(blank=True, help_text='상세 페이지에서 본문 CSS 셀렉터', max_length=500)),
                ('date_format', models.CharField(blank=True, help_text='날짜 포맷 (예: %Y-%m-%d, %Y.%m.%d)', max_length=100)),
                ('date_locale', models.CharField(default='ko_KR', help_text='날짜 로케일 (예: ko_KR, en_US)', max_length=20)),
                ('use_browser', models.BooleanField(default=True, help_text='브라우저 렌더링 사용 여부 (JavaScript 필요 시)')),
                ('wait_selector', models.CharField(blank=True, help_text='페이지 로드 완료 확인용 셀렉터', max_length=500)),
                ('timeout', models.IntegerField(default=30000, help_text='타임아웃 (밀리초)')),
                ('refresh_interval', models.IntegerField(default=60, help_text='새로고침 주기 (분)')),
                ('visible', models.BooleanField(default=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='연결할 RSS 카테고리', null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.rsscategory')),
                ('generated_feed', models.OneToOneField(blank=True, help_text='자동 생성된 RSS 피드', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss_everything_source', to='feeds.rssfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSS Everything Source',
                'verbose_name_plural': 'RSS Everything Sources',
                'indexes': [models.Index(fields=['user'], name='feeds_rssev_user_id_9ea59f_idx'), models.Index(fields=['user', 'visible'], name='feeds_rssev_user_id_724ecc_idx'), models.Index(fields=['category'], name='feeds_rssev_categor_6840df_idx')],
            },
        ),
    ]
