# Generated by Django 5.2.9 on 2025-12-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_rssfeedwithcount_alter_rssfeed_favicon_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSSFeedWithCount',
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='feeds.rsscategory'),
        ),
    ]
