# Generated by Django 5.2.9 on 2025-12-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_rsseverythingsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsseverythingsource',
            name='detail_date_selector',
            field=models.CharField(blank=True, help_text='상세 페이지에서 날짜 CSS 셀렉터', max_length=500),
        ),
        migrations.AddField(
            model_name='rsseverythingsource',
            name='detail_description_selector',
            field=models.CharField(blank=True, help_text='상세 페이지에서 설명/요약 CSS 셀렉터', max_length=500),
        ),
        migrations.AddField(
            model_name='rsseverythingsource',
            name='detail_image_selector',
            field=models.CharField(blank=True, help_text='상세 페이지에서 이미지 CSS 셀렉터', max_length=500),
        ),
        migrations.AddField(
            model_name='rsseverythingsource',
            name='detail_title_selector',
            field=models.CharField(blank=True, help_text='상세 페이지에서 제목 CSS 셀렉터', max_length=500),
        ),
    ]
