# Generated by Django 5.2.9 on 2025-12-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_add_detail_page_selectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsseverythingsource',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict, help_text='HTTP 요청에 사용할 커스텀 헤더'),
        ),
    ]
