# Generated by Django 5.2.9 on 2025-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_add_related_name_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='description_text',
            field=models.TextField(blank=True, default='', help_text='HTML 태그가 제거된 순수 텍스트 (검색용)'),
        ),
    ]
