# Generated by Django 5.2.9 on 2025-12-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_populate_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsseverythingsource',
            name='browser_service',
            field=models.CharField(choices=[('realbrowser', 'RealBrowser (Puppeteer)'), ('browserless', 'Browserless (CDP)')], default='realbrowser', help_text='사용할 브라우저 서비스 (RealBrowser 또는 Browserless)', max_length=20),
        ),
    ]
