# Generated by Django 5.2.9 on 2025-12-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_refactor_rss_everything_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedImage',
        ),
    ]
