# Generated by Django

from django.db import migrations, models


def convert_date_format_to_list(apps, schema_editor):
    """기존 date_format 문자열을 리스트로 변환"""
    RSSEverythingSource = apps.get_model("feeds", "RSSEverythingSource")
    for source in RSSEverythingSource.objects.all():
        if source.date_format:
            # 기존 단일 포맷을 리스트로 변환
            source.date_formats = [source.date_format]
        else:
            source.date_formats = []
        source.save(update_fields=["date_formats"])


def convert_date_formats_to_string(apps, schema_editor):
    """리스트를 다시 문자열로 변환 (롤백용)"""
    RSSEverythingSource = apps.get_model("feeds", "RSSEverythingSource")
    for source in RSSEverythingSource.objects.all():
        if source.date_formats:
            source.date_format = source.date_formats[0]
        else:
            source.date_format = ""
        source.save(update_fields=["date_format"])


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0013_delete_cachedimage"),
    ]

    operations = [
        # 1. 새로운 date_formats 필드 추가
        migrations.AddField(
            model_name="rsseverythingsource",
            name="date_formats",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='날짜 포맷 목록 (예: ["%Y-%m-%d", "%Y.%m.%d %H:%M"])',
            ),
        ),
        # 2. 데이터 마이그레이션
        migrations.RunPython(
            convert_date_format_to_list, convert_date_formats_to_string
        ),
        # 3. 기존 date_format 필드 삭제
        migrations.RemoveField(
            model_name="rsseverythingsource",
            name="date_format",
        ),
    ]
