# Generated by Django 5.2.9 on 2025-12-20 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_add_browser_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='source',
            field=models.ForeignKey(blank=True, help_text='이 아이템을 생성한 소스', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='feeds.rsseverythingsource'),
        ),
    ]
