# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0014_alter_date_formats_to_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsseverythingsource",
            name="exclude_selectors",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text='제외할 CSS 셀렉터 목록 (예: [".ads", ".sidebar", "script"])',
            ),
        ),
    ]
