# Generated by Django 5.2.9 on 2025-12-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_add_source_to_rssitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsseverythingsource',
            name='detail_content_selector',
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='detail_description_selector',
            field=models.CharField(blank=True, help_text='상세 페이지에서 본문 CSS 셀렉터', max_length=500),
        ),
    ]
