# Generated by Django 5.2.9 on 2025-12-23 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_remove_detail_content_selector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rsscategory',
            index=models.Index(fields=['is_public'], name='feeds_rssca_is_publ_879f62_idx'),
        ),
        migrations.AddIndex(
            model_name='rssfeed',
            index=models.Index(fields=['is_public'], name='feeds_rssfe_is_publ_dea8d2_idx'),
        ),
    ]
