# Generated by Django 5.2.9 on 2025-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_rsscategory_feeds_rssca_is_publ_879f62_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text='피드 아이템에 적용할 사용자 정의 CSS'),
        ),
    ]
