# Generated by Django 5.2.9 on 2025-12-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_add_custom_css_to_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='author_selector',
            field=models.CharField(blank=True, default='', help_text='작성자 CSS 셀렉터 (아이템 내부)', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='categories_selector',
            field=models.CharField(blank=True, default='', help_text='카테고리 CSS 셀렉터 (아이템 내부, 여러 개 선택 가능)', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='date_selector',
            field=models.CharField(blank=True, default='', help_text='날짜 CSS 셀렉터 (아이템 내부)', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='description_selector',
            field=models.CharField(blank=True, default='', help_text='설명 CSS 셀렉터 (아이템 내부)', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='detail_author_selector',
            field=models.CharField(blank=True, default='', help_text='상세 페이지 작성자 셀렉터', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='detail_categories_selector',
            field=models.CharField(blank=True, default='', help_text='상세 페이지에서 카테고리 CSS 셀렉터', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='detail_date_selector',
            field=models.CharField(blank=True, default='', help_text='상세 페이지 날짜 셀렉터', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='detail_description_selector',
            field=models.CharField(blank=True, default='', help_text='상세 페이지에서 본문 CSS 셀렉터', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='detail_image_selector',
            field=models.CharField(blank=True, default='', help_text='상세 페이지 이미지 셀렉터', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='detail_title_selector',
            field=models.CharField(blank=True, default='', help_text='상세 페이지 제목 셀렉터', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='image_selector',
            field=models.CharField(blank=True, default='', help_text='이미지 CSS 셀렉터 (아이템 내부)', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='item_selector',
            field=models.CharField(blank=True, default='', help_text='아이템 목록의 CSS 셀렉터 (예: article.post, .news-item)', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='link_selector',
            field=models.CharField(blank=True, default='', help_text='링크 CSS 셀렉터 (아이템 내부, 비워두면 title_selector의 a 태그 사용)', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='title_selector',
            field=models.CharField(blank=True, default='', help_text='제목 CSS 셀렉터 (아이템 내부)', max_length=500),
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='wait_selector',
            field=models.CharField(blank=True, default='', help_text='페이지 로드 완료 확인용 셀렉터', max_length=500),
        ),
    ]
