# Generated by Django 5.2.9 on 2025-12-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_refactor_feed_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsseverythingsource',
            options={'verbose_name': 'RSS Everything Source', 'verbose_name_plural': 'RSS Everything Sources'},
        ),
        migrations.RenameIndex(
            model_name='rsseverythingsource',
            new_name='feeds_rssev_feed_id_3edcd2_idx',
            old_name='feeds_rssev_feed_id_source_idx',
        ),
        migrations.RenameIndex(
            model_name='rsseverythingsource',
            new_name='feeds_rssev_feed_id_094ada_idx',
            old_name='feeds_rssev_feed_id_active_idx',
        ),
        migrations.AlterField(
            model_name='rsseverythingsource',
            name='url',
            field=models.URLField(help_text='RSS URL 또는 크롤링할 페이지 URL'),
        ),
    ]
