x-django-config: &backend
  build:
    context: ./backend
    dockerfile: Dockerfile
  image: drss-backend
  restart: always
  volumes:
    - ./backend:/usr/src/app
  environment:
    - DJANGO_SETTINGS_MODULE=base.settings
    - TZ=Asia/Seoul
  env_file:
    - .env
  networks:
    - drss-dev

services:
  django:
    <<: *backend
    container_name: drss-django
    # Run collectstatic at container start so static files (including admin
    # assets) are available to WhiteNoise before Uvicorn serves requests.
    entrypoint: sh -c "python manage.py collectstatic --noinput && uvicorn base.asgi:application --host 0.0.0.0 --port 8000 --workers 8"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  celery-worker:
    <<: *backend
    container_name: drss-celery-worker
    entrypoint: celery -A base worker --loglevel=info --concurrency 1
    depends_on:
      django:
        condition: service_healthy
  celery-beat:
    <<: *backend
    container_name: drss-celery-beat
    entrypoint: celery -A base beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      django:
        condition: service_healthy
  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: drss-frontend
    container_name: drss-frontend
    restart: always
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules # node_modules는 named volume으로 유지
      - next_cache:/usr/src/app/.next # next.js 캐시를 위한 named volume
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Seoul
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
    env_file:
      - .env
    command: npm run dev
    networks:
      - drss-dev
    depends_on:
      django:
        condition: service_healthy

networks:
  drss-dev:
    driver: bridge

volumes:
  node_modules:
  next_cache:
