/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from '../utils/axiosInstance';
export interface FeedValidationResponse {
  title: string;
  description: string;
  items_count: number;
  latest_item_date?: string;
}

export type FeedValidationRequestCustomHeaders = { [key: string]: unknown };

export interface FeedValidationRequest {
  url: string;
  custom_headers?: FeedValidationRequestCustomHeaders;
}

export type FeedSchemaCustomHeaders = { [key: string]: unknown };

export interface FeedSchema {
  id: number;
  category_id: number;
  url: string;
  title: string;
  favicon_url?: string;
  description: string;
  visible: boolean;
  custom_headers?: FeedSchemaCustomHeaders;
  refresh_interval?: number;
  last_updated: string;
  item_count: number;
}

export type FeedCreateSchemaCustomHeaders = { [key: string]: unknown };

export interface FeedCreateSchema {
  category_id: number;
  url: string;
  title?: string;
  description?: string;
  visible?: boolean;
  custom_headers?: FeedCreateSchemaCustomHeaders;
  refresh_interval?: number;
}

export type FeedUpdateSchemaCategoryId = number | null;

export type FeedUpdateSchemaUrl = string | null;

export type FeedUpdateSchemaTitle = string | null;

export type FeedUpdateSchemaFaviconUrl = string | null;

export type FeedUpdateSchemaDescription = string | null;

export type FeedUpdateSchemaVisible = boolean | null;

export type FeedUpdateSchemaCustomHeadersAnyOf = { [key: string]: unknown };

export type FeedUpdateSchemaCustomHeaders = FeedUpdateSchemaCustomHeadersAnyOf | null;

export type FeedUpdateSchemaRefreshInterval = number | null;

export interface FeedUpdateSchema {
  category_id?: FeedUpdateSchemaCategoryId;
  url?: FeedUpdateSchemaUrl;
  title?: FeedUpdateSchemaTitle;
  favicon_url?: FeedUpdateSchemaFaviconUrl;
  description?: FeedUpdateSchemaDescription;
  visible?: FeedUpdateSchemaVisible;
  custom_headers?: FeedUpdateSchemaCustomHeaders;
  refresh_interval?: FeedUpdateSchemaRefreshInterval;
}

export interface CategorySchema {
  id: number;
  name: string;
  description: string;
}

export interface CategoryCreateSchema {
  name: string;
  description?: string;
}

export interface ItemSchema {
  id: number;
  feed_id: number;
  title: string;
  link: string;
  description: string;
  published_at: string;
  is_read: boolean;
  is_favorite: boolean;
}

export type PaginatedResponseItemSchemaNextCursor = string | null;

export interface PaginatedResponseItemSchema {
  items: ItemSchema[];
  has_next: boolean;
  next_cursor?: PaginatedResponseItemSchemaNextCursor;
}

export interface LoginResponse {
  token: string;
  user: UserResponse;
}

export interface UserResponse {
  id: number;
  username: string;
  email: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface SignupResponse {
  token: string;
  user: UserResponse;
}

export interface SignupRequest {
  username: string;
  password: string;
  email: string;
}

export interface ProtectedResponse {
  message: string;
}

export interface UrlResponse {
  url: string;
}

export interface ErrorResponse {
  error: string;
}

export interface ScheduledResponse {
  status: string;
}

export interface UrlParamSchema {
  url: string;
}

export type FeedsRoutersItemListAllItemsParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
limit?: number;
cursor?: string | null;
direction?: string;
};

export type FeedsRoutersItemListItemsByCategoryParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
limit?: number;
cursor?: string | null;
direction?: string;
};

export type FeedsRoutersItemListItemsByFeedParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
limit?: number;
cursor?: string | null;
direction?: string;
};

export type FeedsRoutersImageCacheImageGetParams = {
url: string;
};

/**
 * @summary Validate Feed
 */
export const feedsRoutersFeedValidateFeed = (
    feedValidationRequest: FeedValidationRequest,
 ) => {
      return axiosInstance<FeedValidationResponse>(
      {url: `/api/feeds/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feedValidationRequest
    },
      );
    }
  
/**
 * @summary List Feeds
 */
export const feedsRoutersFeedListFeeds = (
    
 ) => {
      return axiosInstance<FeedSchema[]>(
      {url: `/api/feeds/feeds`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create Feed
 */
export const feedsRoutersFeedCreateFeed = (
    feedCreateSchema: FeedCreateSchema,
 ) => {
      return axiosInstance<FeedSchema>(
      {url: `/api/feeds/feeds`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feedCreateSchema
    },
      );
    }
  
/**
 * @summary Update Feed
 */
export const feedsRoutersFeedUpdateFeed = (
    feedId: number,
    feedUpdateSchema: FeedUpdateSchema,
 ) => {
      return axiosInstance<FeedSchema>(
      {url: `/api/feeds/${feedId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: feedUpdateSchema
    },
      );
    }
  
/**
 * @summary Delete Feed
 */
export const feedsRoutersFeedDeleteFeed = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Refresh Feed
 */
export const feedsRoutersFeedRefreshFeed = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/refresh`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Mark All Feed Items Read
 */
export const feedsRoutersFeedMarkAllFeedItemsRead = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/mark-all-read`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary Delete All Feed Items
 */
export const feedsRoutersFeedDeleteAllFeedItems = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/items`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary List Categories
 */
export const feedsRoutersCategoryListCategories = (
    
 ) => {
      return axiosInstance<CategorySchema[]>(
      {url: `/api/categories/`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create Category
 */
export const feedsRoutersCategoryCreateCategory = (
    categoryCreateSchema: CategoryCreateSchema,
 ) => {
      return axiosInstance<CategorySchema>(
      {url: `/api/categories/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryCreateSchema
    },
      );
    }
  
/**
 * @summary Update Category
 */
export const feedsRoutersCategoryUpdateCategory = (
    categoryId: number,
    categoryCreateSchema: CategoryCreateSchema,
 ) => {
      return axiosInstance<CategorySchema>(
      {url: `/api/categories/${categoryId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryCreateSchema
    },
      );
    }
  
/**
 * @summary Delete Category
 */
export const feedsRoutersCategoryDeleteCategory = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Refresh Category Feeds
 */
export const feedsRoutersCategoryRefreshCategoryFeeds = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}/refresh`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Get Category Stats
 */
export const feedsRoutersCategoryGetCategoryStats = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}/stats`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Toggle Item Favorite
 */
export const feedsRoutersItemToggleItemFavorite = (
    itemId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/${itemId}/favorite`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary Toggle Item Read
 */
export const feedsRoutersItemToggleItemRead = (
    itemId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/${itemId}/read`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary List All Items
 */
export const feedsRoutersItemListAllItems = (
    params?: FeedsRoutersItemListAllItemsParams,
 ) => {
      return axiosInstance<PaginatedResponseItemSchema>(
      {url: `/api/items/`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary List Items By Category
 */
export const feedsRoutersItemListItemsByCategory = (
    categoryId: number,
    params?: FeedsRoutersItemListItemsByCategoryParams,
 ) => {
      return axiosInstance<PaginatedResponseItemSchema>(
      {url: `/api/items/category/${categoryId}`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary List Items By Feed
 */
export const feedsRoutersItemListItemsByFeed = (
    feedId: number,
    params?: FeedsRoutersItemListItemsByFeedParams,
 ) => {
      return axiosInstance<PaginatedResponseItemSchema>(
      {url: `/api/items/feed/${feedId}`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary Login
 */
export const usersRouterLogin = (
    loginRequest: LoginRequest,
 ) => {
      return axiosInstance<LoginResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  
/**
 * @summary Signup
 */
export const usersRouterSignup = (
    signupRequest: SignupRequest,
 ) => {
      return axiosInstance<SignupResponse>(
      {url: `/api/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest
    },
      );
    }
  
/**
 * @summary Protected
 */
export const usersRouterProtected = (
    
 ) => {
      return axiosInstance<ProtectedResponse>(
      {url: `/api/auth/protected`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Me
 */
export const usersRouterMe = (
    
 ) => {
      return axiosInstance<UserResponse>(
      {url: `/api/auth/me`, method: 'GET'
    },
      );
    }
  
/**
 * GET: return cached image URL if available; do NOT schedule on GET.
 * @summary Cache Image Get
 */
export const feedsRoutersImageCacheImageGet = (
    params: FeedsRoutersImageCacheImageGetParams,
 ) => {
      return axiosInstance<UrlResponse>(
      {url: `/api/images/`, method: 'GET',
        params
    },
      );
    }
  
/**
 * POST: schedule caching if not present; return 200 with url if already cached, or 202 if scheduled.
 * @summary Cache Image Post
 */
export const feedsRoutersImageCacheImagePost = (
    urlParamSchema: UrlParamSchema,
 ) => {
      return axiosInstance<UrlResponse | ScheduledResponse>(
      {url: `/api/images/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: urlParamSchema
    },
      );
    }
  
export type FeedsRoutersFeedValidateFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedValidateFeed>>>
export type FeedsRoutersFeedListFeedsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedListFeeds>>>
export type FeedsRoutersFeedCreateFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedCreateFeed>>>
export type FeedsRoutersFeedUpdateFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedUpdateFeed>>>
export type FeedsRoutersFeedDeleteFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedDeleteFeed>>>
export type FeedsRoutersFeedRefreshFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedRefreshFeed>>>
export type FeedsRoutersFeedMarkAllFeedItemsReadResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedMarkAllFeedItemsRead>>>
export type FeedsRoutersFeedDeleteAllFeedItemsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedDeleteAllFeedItems>>>
export type FeedsRoutersCategoryListCategoriesResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryListCategories>>>
export type FeedsRoutersCategoryCreateCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryCreateCategory>>>
export type FeedsRoutersCategoryUpdateCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryUpdateCategory>>>
export type FeedsRoutersCategoryDeleteCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryDeleteCategory>>>
export type FeedsRoutersCategoryRefreshCategoryFeedsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryRefreshCategoryFeeds>>>
export type FeedsRoutersCategoryGetCategoryStatsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryGetCategoryStats>>>
export type FeedsRoutersItemToggleItemFavoriteResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemToggleItemFavorite>>>
export type FeedsRoutersItemToggleItemReadResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemToggleItemRead>>>
export type FeedsRoutersItemListAllItemsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemListAllItems>>>
export type FeedsRoutersItemListItemsByCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemListItemsByCategory>>>
export type FeedsRoutersItemListItemsByFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemListItemsByFeed>>>
export type UsersRouterLoginResult = NonNullable<Awaited<ReturnType<typeof usersRouterLogin>>>
export type UsersRouterSignupResult = NonNullable<Awaited<ReturnType<typeof usersRouterSignup>>>
export type UsersRouterProtectedResult = NonNullable<Awaited<ReturnType<typeof usersRouterProtected>>>
export type UsersRouterMeResult = NonNullable<Awaited<ReturnType<typeof usersRouterMe>>>
export type FeedsRoutersImageCacheImageGetResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersImageCacheImageGet>>>
export type FeedsRoutersImageCacheImagePostResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersImageCacheImagePost>>>
