/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from '../utils/axiosInstance';
export interface LoginResponse {
  token: string;
  user: UserResponse;
}

export interface UserResponse {
  id: number;
  username: string;
  email: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface SignupResponse {
  token: string;
  user: UserResponse;
}

export interface SignupRequest {
  username: string;
  password: string;
  email: string;
}

export interface ProtectedResponse {
  message: string;
}

export interface FeedValidationResponse {
  title: string;
  description: string;
  items_count: number;
  latest_item_date?: string;
}

export type FeedValidationRequestCustomHeaders = { [key: string]: unknown };

export interface FeedValidationRequest {
  url: string;
  custom_headers?: FeedValidationRequestCustomHeaders;
}

export interface CategorySchema {
  id: number;
  name: string;
  description: string;
}

export interface CategoryCreateSchema {
  name: string;
  description?: string;
}

export type FeedSchemaCustomHeaders = { [key: string]: unknown };

export interface FeedSchema {
  id: number;
  category_id: number;
  url: string;
  title: string;
  favicon_url?: string;
  description: string;
  visible: boolean;
  custom_headers?: FeedSchemaCustomHeaders;
  refresh_interval?: number;
  last_updated: string;
}

export type FeedCreateSchemaCustomHeaders = { [key: string]: unknown };

export interface FeedCreateSchema {
  category_id: number;
  url: string;
  title?: string;
  description?: string;
  visible?: boolean;
  custom_headers?: FeedCreateSchemaCustomHeaders;
  refresh_interval?: number;
}

export interface ItemSchema {
  id: number;
  feed_id: number;
  title: string;
  link: string;
  description: string;
  published_at: string;
  is_read: boolean;
  is_favorite: boolean;
}

export type FeedsRouterListAllItemsParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
};

/**
 * @summary Login
 */
export const usersRouterLogin = (
    loginRequest: LoginRequest,
 ) => {
      return axiosInstance<LoginResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  
/**
 * @summary Signup
 */
export const usersRouterSignup = (
    signupRequest: SignupRequest,
 ) => {
      return axiosInstance<SignupResponse>(
      {url: `/api/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest
    },
      );
    }
  
/**
 * @summary Protected
 */
export const usersRouterProtected = (
    
 ) => {
      return axiosInstance<ProtectedResponse>(
      {url: `/api/auth/protected`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Me
 */
export const usersRouterMe = (
    
 ) => {
      return axiosInstance<UserResponse>(
      {url: `/api/auth/me`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Validate Feed
 */
export const feedsRouterValidateFeed = (
    feedValidationRequest: FeedValidationRequest,
 ) => {
      return axiosInstance<FeedValidationResponse>(
      {url: `/api/feeds/feeds/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feedValidationRequest
    },
      );
    }
  
/**
 * @summary List Categories
 */
export const feedsRouterListCategories = (
    
 ) => {
      return axiosInstance<CategorySchema[]>(
      {url: `/api/feeds/categories`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create Category
 */
export const feedsRouterCreateCategory = (
    categoryCreateSchema: CategoryCreateSchema,
 ) => {
      return axiosInstance<CategorySchema>(
      {url: `/api/feeds/categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryCreateSchema
    },
      );
    }
  
/**
 * @summary Update Category
 */
export const feedsRouterUpdateCategory = (
    categoryId: number,
    categoryCreateSchema: CategoryCreateSchema,
 ) => {
      return axiosInstance<CategorySchema>(
      {url: `/api/feeds/categories/${categoryId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryCreateSchema
    },
      );
    }
  
/**
 * @summary Delete Category
 */
export const feedsRouterDeleteCategory = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/categories/${categoryId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary List Feeds
 */
export const feedsRouterListFeeds = (
    
 ) => {
      return axiosInstance<FeedSchema[]>(
      {url: `/api/feeds/feeds`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create Feed
 */
export const feedsRouterCreateFeed = (
    feedCreateSchema: FeedCreateSchema,
 ) => {
      return axiosInstance<FeedSchema>(
      {url: `/api/feeds/feeds`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feedCreateSchema
    },
      );
    }
  
/**
 * @summary Delete Feed
 */
export const feedsRouterDeleteFeed = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/feeds/${feedId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary List Feed Items
 */
export const feedsRouterListFeedItems = (
    feedId: number,
 ) => {
      return axiosInstance<ItemSchema[]>(
      {url: `/api/feeds/feeds/${feedId}/items`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Mark Item Read
 */
export const feedsRouterMarkItemRead = (
    itemId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/items/${itemId}/read`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary Toggle Item Favorite
 */
export const feedsRouterToggleItemFavorite = (
    itemId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/items/${itemId}/favorite`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary List All Items
 */
export const feedsRouterListAllItems = (
    params?: FeedsRouterListAllItemsParams,
 ) => {
      return axiosInstance<ItemSchema[]>(
      {url: `/api/feeds/items`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary Get Category Stats
 */
export const feedsRouterGetCategoryStats = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/categories/${categoryId}/stats`, method: 'GET'
    },
      );
    }
  
export type UsersRouterLoginResult = NonNullable<Awaited<ReturnType<typeof usersRouterLogin>>>
export type UsersRouterSignupResult = NonNullable<Awaited<ReturnType<typeof usersRouterSignup>>>
export type UsersRouterProtectedResult = NonNullable<Awaited<ReturnType<typeof usersRouterProtected>>>
export type UsersRouterMeResult = NonNullable<Awaited<ReturnType<typeof usersRouterMe>>>
export type FeedsRouterValidateFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRouterValidateFeed>>>
export type FeedsRouterListCategoriesResult = NonNullable<Awaited<ReturnType<typeof feedsRouterListCategories>>>
export type FeedsRouterCreateCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRouterCreateCategory>>>
export type FeedsRouterUpdateCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRouterUpdateCategory>>>
export type FeedsRouterDeleteCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRouterDeleteCategory>>>
export type FeedsRouterListFeedsResult = NonNullable<Awaited<ReturnType<typeof feedsRouterListFeeds>>>
export type FeedsRouterCreateFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRouterCreateFeed>>>
export type FeedsRouterDeleteFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRouterDeleteFeed>>>
export type FeedsRouterListFeedItemsResult = NonNullable<Awaited<ReturnType<typeof feedsRouterListFeedItems>>>
export type FeedsRouterMarkItemReadResult = NonNullable<Awaited<ReturnType<typeof feedsRouterMarkItemRead>>>
export type FeedsRouterToggleItemFavoriteResult = NonNullable<Awaited<ReturnType<typeof feedsRouterToggleItemFavorite>>>
export type FeedsRouterListAllItemsResult = NonNullable<Awaited<ReturnType<typeof feedsRouterListAllItems>>>
export type FeedsRouterGetCategoryStatsResult = NonNullable<Awaited<ReturnType<typeof feedsRouterGetCategoryStats>>>
