/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from '../utils/axiosInstance';
export type FeedValidationResponseLatestItemDate = string | null;

/**
 * 피드 검증 응답
 */
export interface FeedValidationResponse {
  title: string;
  description: string;
  items_count: number;
  latest_item_date?: FeedValidationResponseLatestItemDate;
}

export type FeedValidationRequestCustomHeaders = { [key: string]: unknown };

/**
 * 피드 검증 요청
 */
export interface FeedValidationRequest {
  url: string;
  custom_headers?: FeedValidationRequestCustomHeaders;
}

/**
 * 피드 스키마
 */
export interface FeedSchema {
  id: number;
  category_id: number;
  title: string;
  favicon_url?: string;
  description: string;
  visible: boolean;
  refresh_interval?: number;
  last_updated: string;
  item_count: number;
  sources?: SourceSchema[];
}

export type SourceSchemaSourceType = typeof SourceSchemaSourceType[keyof typeof SourceSchemaSourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourceSchemaSourceType = {
  rss: 'rss',
  page_scraping: 'page_scraping',
  detail_page_scraping: 'detail_page_scraping',
} as const;

export type SourceSchemaCustomHeaders = { [key: string]: unknown };

export type SourceSchemaLastCrawledAt = string | null;

/**
 * 소스 스키마
 */
export interface SourceSchema {
  id: number;
  feed_id: number;
  source_type: SourceSchemaSourceType;
  is_active: boolean;
  url: string;
  custom_headers?: SourceSchemaCustomHeaders;
  item_selector?: string;
  title_selector?: string;
  link_selector?: string;
  description_selector?: string;
  date_selector?: string;
  image_selector?: string;
  detail_title_selector?: string;
  detail_description_selector?: string;
  detail_content_selector?: string;
  detail_date_selector?: string;
  detail_image_selector?: string;
  exclude_selectors?: string[];
  date_formats?: string[];
  date_locale?: string;
  use_browser?: boolean;
  wait_selector?: string;
  timeout?: number;
  last_crawled_at?: SourceSchemaLastCrawledAt;
  last_error?: string;
}

export type FeedCreateSchemaSource = SourceCreateSchema | null;

/**
 * 피드 생성 스키마 - 소스 정보는 선택적
 */
export interface FeedCreateSchema {
  category_id: number;
  title?: string;
  description?: string;
  visible?: boolean;
  refresh_interval?: number;
  source?: FeedCreateSchemaSource;
}

export type SourceCreateSchemaSourceType = typeof SourceCreateSchemaSourceType[keyof typeof SourceCreateSchemaSourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourceCreateSchemaSourceType = {
  rss: 'rss',
  page_scraping: 'page_scraping',
  detail_page_scraping: 'detail_page_scraping',
} as const;

export type SourceCreateSchemaCustomHeaders = { [key: string]: unknown };

/**
 * 소스 생성 스키마
 */
export interface SourceCreateSchema {
  source_type?: SourceCreateSchemaSourceType;
  url: string;
  custom_headers?: SourceCreateSchemaCustomHeaders;
  item_selector?: string;
  title_selector?: string;
  link_selector?: string;
  description_selector?: string;
  date_selector?: string;
  image_selector?: string;
  author_selector?: string;
  categories_selector?: string;
  detail_title_selector?: string;
  detail_description_selector?: string;
  detail_content_selector?: string;
  detail_date_selector?: string;
  detail_image_selector?: string;
  detail_author_selector?: string;
  detail_categories_selector?: string;
  exclude_selectors?: string[];
  date_formats?: string[];
  date_locale?: string;
  use_browser?: boolean;
  wait_selector?: string;
  timeout?: number;
}

export type FeedUpdateSchemaCategoryId = number | null;

export type FeedUpdateSchemaTitle = string | null;

export type FeedUpdateSchemaFaviconUrl = string | null;

export type FeedUpdateSchemaDescription = string | null;

export type FeedUpdateSchemaVisible = boolean | null;

export type FeedUpdateSchemaRefreshInterval = number | null;

/**
 * 피드 수정 스키마
 */
export interface FeedUpdateSchema {
  category_id?: FeedUpdateSchemaCategoryId;
  title?: FeedUpdateSchemaTitle;
  favicon_url?: FeedUpdateSchemaFaviconUrl;
  description?: FeedUpdateSchemaDescription;
  visible?: FeedUpdateSchemaVisible;
  refresh_interval?: FeedUpdateSchemaRefreshInterval;
}

export type SourceUpdateSchemaSourceType = 'rss' | 'page_scraping' | 'detail_page_scraping' | null;

export type SourceUpdateSchemaIsActive = boolean | null;

export type SourceUpdateSchemaUrl = string | null;

export type SourceUpdateSchemaCustomHeadersAnyOf = { [key: string]: unknown };

export type SourceUpdateSchemaCustomHeaders = SourceUpdateSchemaCustomHeadersAnyOf | null;

export type SourceUpdateSchemaItemSelector = string | null;

export type SourceUpdateSchemaTitleSelector = string | null;

export type SourceUpdateSchemaLinkSelector = string | null;

export type SourceUpdateSchemaDescriptionSelector = string | null;

export type SourceUpdateSchemaDateSelector = string | null;

export type SourceUpdateSchemaImageSelector = string | null;

export type SourceUpdateSchemaAuthorSelector = string | null;

export type SourceUpdateSchemaCategoriesSelector = string | null;

export type SourceUpdateSchemaDetailTitleSelector = string | null;

export type SourceUpdateSchemaDetailDescriptionSelector = string | null;

export type SourceUpdateSchemaDetailContentSelector = string | null;

export type SourceUpdateSchemaDetailDateSelector = string | null;

export type SourceUpdateSchemaDetailImageSelector = string | null;

export type SourceUpdateSchemaDetailAuthorSelector = string | null;

export type SourceUpdateSchemaDetailCategoriesSelector = string | null;

export type SourceUpdateSchemaExcludeSelectors = string[] | null;

export type SourceUpdateSchemaDateFormats = string[] | null;

export type SourceUpdateSchemaDateLocale = string | null;

export type SourceUpdateSchemaUseBrowser = boolean | null;

export type SourceUpdateSchemaWaitSelector = string | null;

export type SourceUpdateSchemaTimeout = number | null;

/**
 * 소스 업데이트 스키마
 */
export interface SourceUpdateSchema {
  source_type?: SourceUpdateSchemaSourceType;
  is_active?: SourceUpdateSchemaIsActive;
  url?: SourceUpdateSchemaUrl;
  custom_headers?: SourceUpdateSchemaCustomHeaders;
  item_selector?: SourceUpdateSchemaItemSelector;
  title_selector?: SourceUpdateSchemaTitleSelector;
  link_selector?: SourceUpdateSchemaLinkSelector;
  description_selector?: SourceUpdateSchemaDescriptionSelector;
  date_selector?: SourceUpdateSchemaDateSelector;
  image_selector?: SourceUpdateSchemaImageSelector;
  author_selector?: SourceUpdateSchemaAuthorSelector;
  categories_selector?: SourceUpdateSchemaCategoriesSelector;
  detail_title_selector?: SourceUpdateSchemaDetailTitleSelector;
  detail_description_selector?: SourceUpdateSchemaDetailDescriptionSelector;
  detail_content_selector?: SourceUpdateSchemaDetailContentSelector;
  detail_date_selector?: SourceUpdateSchemaDetailDateSelector;
  detail_image_selector?: SourceUpdateSchemaDetailImageSelector;
  detail_author_selector?: SourceUpdateSchemaDetailAuthorSelector;
  detail_categories_selector?: SourceUpdateSchemaDetailCategoriesSelector;
  exclude_selectors?: SourceUpdateSchemaExcludeSelectors;
  date_formats?: SourceUpdateSchemaDateFormats;
  date_locale?: SourceUpdateSchemaDateLocale;
  use_browser?: SourceUpdateSchemaUseBrowser;
  wait_selector?: SourceUpdateSchemaWaitSelector;
  timeout?: SourceUpdateSchemaTimeout;
}

/**
 * 카테고리 + 피드 목록 스키마 (초기 로딩용)
 */
export interface CategoryWithFeedsSchema {
  id: number;
  name: string;
  description: string;
  visible: boolean;
  order: number;
  feeds?: FeedSchema[];
}

/**
 * 카테고리 스키마
 */
export interface CategorySchema {
  id: number;
  name: string;
  description: string;
  visible: boolean;
  order: number;
}

/**
 * 카테고리 생성 스키마
 */
export interface CategoryCreateSchema {
  name: string;
  description?: string;
  visible?: boolean;
}

export type CategoryUpdateSchemaName = string | null;

export type CategoryUpdateSchemaDescription = string | null;

export type CategoryUpdateSchemaVisible = boolean | null;

export type CategoryUpdateSchemaOrder = number | null;

/**
 * 카테고리 수정 스키마
 */
export interface CategoryUpdateSchema {
  name?: CategoryUpdateSchemaName;
  description?: CategoryUpdateSchemaDescription;
  visible?: CategoryUpdateSchemaVisible;
  order?: CategoryUpdateSchemaOrder;
}

/**
 * 카테고리 순서 변경 스키마
 */
export interface CategoryReorderSchema {
  category_ids: number[];
}

export type InputCursor = string | null;

export type InputOrderingField = string | null;

export interface Input {
  cursor?: InputCursor;
  limit?: number;
  direction?: string;
  ordering_field?: InputOrderingField;
}

/**
 * 아이템 스키마
 */
export interface ItemSchema {
  id: number;
  feed_id: number;
  title: string;
  link: string;
  description: string;
  author?: string;
  categories?: string[];
  image?: string;
  published_at: string;
  is_read: boolean;
  is_favorite: boolean;
}

export type PagedItemSchemaNextCursor = string | null;

export type PagedItemSchemaPrevCursor = string | null;

export interface PagedItemSchema {
  items: ItemSchema[];
  next_cursor?: PagedItemSchemaNextCursor;
  prev_cursor?: PagedItemSchemaPrevCursor;
  has_next?: boolean;
  has_prev?: boolean;
}

export interface LoginResponse {
  token: string;
  user: UserResponse;
}

export interface UserResponse {
  id: number;
  username: string;
  email: string;
  is_staff: boolean;
  is_superuser: boolean;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface SignupResponse {
  token: string;
  user: UserResponse;
}

export interface SignupRequest {
  username: string;
  password: string;
  email: string;
}

export interface ProtectedResponse {
  message: string;
}

/**
 * 글로벌 설정 스키마
 */
export interface GlobalSettingSchema {
  admin_signed: boolean;
  allow_signup: boolean;
  site_name: string;
  max_feeds_per_user: number;
  default_refresh_interval: number;
}

export type GlobalSettingUpdateSchemaAllowSignup = boolean | null;

export type GlobalSettingUpdateSchemaSiteName = string | null;

export type GlobalSettingUpdateSchemaMaxFeedsPerUser = number | null;

export type GlobalSettingUpdateSchemaDefaultRefreshInterval = number | null;

/**
 * 글로벌 설정 업데이트 스키마 (부분 업데이트 가능)
 */
export interface GlobalSettingUpdateSchema {
  allow_signup?: GlobalSettingUpdateSchemaAllowSignup;
  site_name?: GlobalSettingUpdateSchemaSiteName;
  max_feeds_per_user?: GlobalSettingUpdateSchemaMaxFeedsPerUser;
  default_refresh_interval?: GlobalSettingUpdateSchemaDefaultRefreshInterval;
}

export interface SignupStatusSchema {
  allow_signup: boolean;
  site_name: string;
}

export type FetchHTMLResponseHtml = string | null;

export type FetchHTMLResponseError = string | null;

/**
 * HTML 가져오기 응답
 */
export interface FetchHTMLResponse {
  success: boolean;
  html?: FetchHTMLResponseHtml;
  url: string;
  error?: FetchHTMLResponseError;
}

export type FetchHTMLRequestCustomHeaders = { [key: string]: unknown };

/**
 * HTML 가져오기 요청
 */
export interface FetchHTMLRequest {
  url: string;
  use_browser?: boolean;
  wait_selector?: string;
  timeout?: number;
  custom_headers?: FetchHTMLRequestCustomHeaders;
}

export type ElementInfoHref = string | null;

export type ElementInfoSrc = string | null;

/**
 * 추출된 요소 정보
 */
export interface ElementInfo {
  tag: string;
  text: string;
  html: string;
  href?: ElementInfoHref;
  src?: ElementInfoSrc;
  selector: string;
}

export type ExtractElementsResponseError = string | null;

/**
 * 요소 추출 응답
 */
export interface ExtractElementsResponse {
  success: boolean;
  elements?: ElementInfo[];
  count?: number;
  error?: ExtractElementsResponseError;
}

/**
 * 요소 추출 요청
 */
export interface ExtractElementsRequest {
  html: string;
  selector: string;
  base_url: string;
}

/**
 * 미리보기 아이템
 */
export interface PreviewItem {
  title: string;
  link: string;
  description?: string;
  date?: string;
  image?: string;
}

export type PreviewItemResponseError = string | null;

/**
 * 아이템 미리보기 응답
 */
export interface PreviewItemResponse {
  success: boolean;
  items?: PreviewItem[];
  count?: number;
  error?: PreviewItemResponseError;
}

export type PreviewItemRequestCustomHeaders = { [key: string]: unknown };

/**
 * 아이템 미리보기 요청
 */
export interface PreviewItemRequest {
  url: string;
  item_selector: string;
  title_selector?: string;
  link_selector?: string;
  description_selector?: string;
  date_selector?: string;
  image_selector?: string;
  use_browser?: boolean;
  wait_selector?: string;
  custom_headers?: PreviewItemRequestCustomHeaders;
  exclude_selectors?: string[];
  follow_links?: boolean;
  detail_title_selector?: string;
  detail_description_selector?: string;
  detail_content_selector?: string;
  detail_date_selector?: string;
  detail_image_selector?: string;
}

export type RSSEverythingSchemaCustomHeaders = { [key: string]: unknown };

export type RSSEverythingSchemaLastCrawledAt = string | null;

/**
 * RSSEverything 소스 스키마
 */
export interface RSSEverythingSchema {
  id: number;
  feed_id: number;
  url: string;
  source_type: string;
  is_active: boolean;
  item_selector: string;
  title_selector: string;
  link_selector: string;
  description_selector: string;
  date_selector: string;
  image_selector: string;
  author_selector: string;
  categories_selector: string;
  follow_links: boolean;
  detail_title_selector: string;
  detail_description_selector: string;
  detail_content_selector: string;
  detail_date_selector: string;
  detail_image_selector: string;
  detail_author_selector: string;
  detail_categories_selector: string;
  exclude_selectors: string[];
  date_formats: string[];
  date_locale: string;
  use_browser: boolean;
  wait_selector: string;
  timeout: number;
  custom_headers: RSSEverythingSchemaCustomHeaders;
  last_crawled_at: RSSEverythingSchemaLastCrawledAt;
  last_error: string;
  created_at: string;
  updated_at: string;
}

export type RSSEverythingCreateRequestCustomHeaders = { [key: string]: unknown };

/**
 * RSSEverything 소스 생성 요청
 */
export interface RSSEverythingCreateRequest {
  feed_id: number;
  url: string;
  source_type?: string;
  custom_headers?: RSSEverythingCreateRequestCustomHeaders;
  item_selector?: string;
  title_selector?: string;
  link_selector?: string;
  description_selector?: string;
  date_selector?: string;
  image_selector?: string;
  author_selector?: string;
  categories_selector?: string;
  follow_links?: boolean;
  detail_title_selector?: string;
  detail_description_selector?: string;
  detail_content_selector?: string;
  detail_date_selector?: string;
  detail_image_selector?: string;
  detail_author_selector?: string;
  detail_categories_selector?: string;
  exclude_selectors?: string[];
  date_formats?: string[];
  date_locale?: string;
  use_browser?: boolean;
  wait_selector?: string;
  timeout?: number;
}

export type RSSEverythingUpdateRequestUrl = string | null;

export type RSSEverythingUpdateRequestSourceType = string | null;

export type RSSEverythingUpdateRequestCustomHeadersAnyOf = { [key: string]: unknown };

export type RSSEverythingUpdateRequestCustomHeaders = RSSEverythingUpdateRequestCustomHeadersAnyOf | null;

export type RSSEverythingUpdateRequestIsActive = boolean | null;

export type RSSEverythingUpdateRequestItemSelector = string | null;

export type RSSEverythingUpdateRequestTitleSelector = string | null;

export type RSSEverythingUpdateRequestLinkSelector = string | null;

export type RSSEverythingUpdateRequestDescriptionSelector = string | null;

export type RSSEverythingUpdateRequestDateSelector = string | null;

export type RSSEverythingUpdateRequestImageSelector = string | null;

export type RSSEverythingUpdateRequestAuthorSelector = string | null;

export type RSSEverythingUpdateRequestCategoriesSelector = string | null;

export type RSSEverythingUpdateRequestFollowLinks = boolean | null;

export type RSSEverythingUpdateRequestDetailTitleSelector = string | null;

export type RSSEverythingUpdateRequestDetailDescriptionSelector = string | null;

export type RSSEverythingUpdateRequestDetailContentSelector = string | null;

export type RSSEverythingUpdateRequestDetailDateSelector = string | null;

export type RSSEverythingUpdateRequestDetailImageSelector = string | null;

export type RSSEverythingUpdateRequestDetailAuthorSelector = string | null;

export type RSSEverythingUpdateRequestDetailCategoriesSelector = string | null;

export type RSSEverythingUpdateRequestExcludeSelectors = string[] | null;

export type RSSEverythingUpdateRequestDateFormats = string[] | null;

export type RSSEverythingUpdateRequestDateLocale = string | null;

export type RSSEverythingUpdateRequestUseBrowser = boolean | null;

export type RSSEverythingUpdateRequestWaitSelector = string | null;

export type RSSEverythingUpdateRequestTimeout = number | null;

/**
 * RSSEverything 소스 수정 요청
 */
export interface RSSEverythingUpdateRequest {
  url?: RSSEverythingUpdateRequestUrl;
  source_type?: RSSEverythingUpdateRequestSourceType;
  custom_headers?: RSSEverythingUpdateRequestCustomHeaders;
  is_active?: RSSEverythingUpdateRequestIsActive;
  item_selector?: RSSEverythingUpdateRequestItemSelector;
  title_selector?: RSSEverythingUpdateRequestTitleSelector;
  link_selector?: RSSEverythingUpdateRequestLinkSelector;
  description_selector?: RSSEverythingUpdateRequestDescriptionSelector;
  date_selector?: RSSEverythingUpdateRequestDateSelector;
  image_selector?: RSSEverythingUpdateRequestImageSelector;
  author_selector?: RSSEverythingUpdateRequestAuthorSelector;
  categories_selector?: RSSEverythingUpdateRequestCategoriesSelector;
  follow_links?: RSSEverythingUpdateRequestFollowLinks;
  detail_title_selector?: RSSEverythingUpdateRequestDetailTitleSelector;
  detail_description_selector?: RSSEverythingUpdateRequestDetailDescriptionSelector;
  detail_content_selector?: RSSEverythingUpdateRequestDetailContentSelector;
  detail_date_selector?: RSSEverythingUpdateRequestDetailDateSelector;
  detail_image_selector?: RSSEverythingUpdateRequestDetailImageSelector;
  detail_author_selector?: RSSEverythingUpdateRequestDetailAuthorSelector;
  detail_categories_selector?: RSSEverythingUpdateRequestDetailCategoriesSelector;
  exclude_selectors?: RSSEverythingUpdateRequestExcludeSelectors;
  date_formats?: RSSEverythingUpdateRequestDateFormats;
  date_locale?: RSSEverythingUpdateRequestDateLocale;
  use_browser?: RSSEverythingUpdateRequestUseBrowser;
  wait_selector?: RSSEverythingUpdateRequestWaitSelector;
  timeout?: RSSEverythingUpdateRequestTimeout;
}

/**
 * 새로고침 응답
 */
export interface RefreshResponse {
  success: boolean;
  task_result_id: number;
  message: string;
}

/**
 * 피드 기본 정보
 */
export interface FeedInfo {
  id: number;
  title: string;
}

export type PagedTaskResultSchemaNextCursor = string | null;

export type PagedTaskResultSchemaPrevCursor = string | null;

export interface PagedTaskResultSchema {
  items: TaskResultSchema[];
  next_cursor?: PagedTaskResultSchemaNextCursor;
  prev_cursor?: PagedTaskResultSchemaPrevCursor;
  has_next?: boolean;
  has_prev?: boolean;
}

export type TaskResultSchemaStartedAt = string | null;

export type TaskResultSchemaCompletedAt = string | null;

export type TaskResultSchemaDurationSeconds = number | null;

/**
 * 태스크 결과 스키마
 */
export interface TaskResultSchema {
  id: number;
  feed: FeedInfo;
  task_id: string;
  status: string;
  items_found: number;
  items_created: number;
  error_message: string;
  started_at: TaskResultSchemaStartedAt;
  completed_at: TaskResultSchemaCompletedAt;
  created_at: string;
  duration_seconds: TaskResultSchemaDurationSeconds;
}

/**
 * 태스크 통계
 */
export interface TaskStatsSchema {
  total: number;
  success: number;
  failure: number;
  pending: number;
  running: number;
}

/**
 * 인터벌 스케줄 스키마
 */
export interface IntervalScheduleSchema {
  every: number;
  period: string;
}

/**
 * 주기적 태스크 목록 응답
 */
export interface PeriodicTaskListResponse {
  items: PeriodicTaskSchema[];
  total: number;
}

export type PeriodicTaskSchemaFeedId = number | null;

export type PeriodicTaskSchemaFeedTitle = string | null;

export type PeriodicTaskSchemaInterval = IntervalScheduleSchema | null;

export type PeriodicTaskSchemaLastRunAt = string | null;

export type PeriodicTaskSchemaDateChanged = string | null;

/**
 * 주기적 태스크 스키마
 */
export interface PeriodicTaskSchema {
  id: number;
  name: string;
  task: string;
  feed_id: PeriodicTaskSchemaFeedId;
  feed_title: PeriodicTaskSchemaFeedTitle;
  enabled: boolean;
  interval: PeriodicTaskSchemaInterval;
  last_run_at: PeriodicTaskSchemaLastRunAt;
  total_run_count: number;
  date_changed: PeriodicTaskSchemaDateChanged;
}

export type PeriodicTaskUpdateSchemaEnabled = boolean | null;

export type PeriodicTaskUpdateSchemaIntervalMinutes = number | null;

/**
 * 주기적 태스크 업데이트 스키마
 */
export interface PeriodicTaskUpdateSchema {
  enabled?: PeriodicTaskUpdateSchemaEnabled;
  interval_minutes?: PeriodicTaskUpdateSchemaIntervalMinutes;
}

export type ListAllItemsParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
cursor?: string | null;
limit?: number;
direction?: string;
ordering_field?: string | null;
};

export type ListItemsByCategoryParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
cursor?: string | null;
limit?: number;
direction?: string;
ordering_field?: string | null;
};

export type ListItemsByFeedParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
cursor?: string | null;
limit?: number;
direction?: string;
ordering_field?: string | null;
};

export type ExportAllItemsRssParams = {
page?: number;
page_size?: number;
format?: string;
};

export type ExportCategoryItemsRssParams = {
page?: number;
page_size?: number;
format?: string;
};

export type ExportFeedItemsRssParams = {
page?: number;
page_size?: number;
format?: string;
};

export type ListTaskResultsParams = {
feed_id?: number | null;
status?: string | null;
cursor?: string | null;
limit?: number;
direction?: string;
ordering_field?: string | null;
};

export type ClearTaskResultsParams = {
feed_id?: number | null;
status?: string | null;
};

export type GetTaskStatsParams = {
feed_id?: number | null;
};

export type ListPeriodicTasksParams = {
feed_id?: number | null;
enabled?: boolean | null;
limit?: number;
offset?: number;
};

/**
 * @summary Health Check
 */
export const baseApiHealthCheck = (
    
 ) => {
      return axiosInstance<void>(
      {url: `/api/health`, method: 'GET'
    },
      );
    }
  
/**
 * RSS 피드 URL 검증
 * @summary Validate Feed
 */
export const validateFeed = (
    feedValidationRequest: FeedValidationRequest,
 ) => {
      return axiosInstance<FeedValidationResponse>(
      {url: `/api/feeds/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feedValidationRequest
    },
      );
    }
  
/**
 * 피드 목록 조회
 * @summary List Feeds
 */
export const listFeeds = (
    
 ) => {
      return axiosInstance<FeedSchema[]>(
      {url: `/api/feeds`, method: 'GET'
    },
      );
    }
  
/**
 * 피드 생성
 * @summary Create Feed
 */
export const createFeed = (
    feedCreateSchema: FeedCreateSchema,
 ) => {
      return axiosInstance<FeedSchema>(
      {url: `/api/feeds`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feedCreateSchema
    },
      );
    }
  
/**
 * 피드 수정
 * @summary Update Feed
 */
export const updateFeed = (
    feedId: number,
    feedUpdateSchema: FeedUpdateSchema,
 ) => {
      return axiosInstance<FeedSchema>(
      {url: `/api/feeds/${feedId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: feedUpdateSchema
    },
      );
    }
  
/**
 * 피드 삭제
 * @summary Delete Feed
 */
export const deleteFeed = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * 피드 새로고침
 * @summary Refresh Feed
 */
export const refreshFeed = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/refresh`, method: 'POST'
    },
      );
    }
  
/**
 * 피드의 모든 아이템을 읽음 처리
 * @summary Mark All Feed Items Read
 */
export const markAllFeedItemsRead = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/mark-all-read`, method: 'PUT'
    },
      );
    }
  
/**
 * 피드의 모든 아이템 삭제
 * @summary Delete All Feed Items
 */
export const deleteAllFeedItems = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/items`, method: 'DELETE'
    },
      );
    }
  
/**
 * 피드에 새 소스 추가
 * @summary Add Source
 */
export const addFeedSource = (
    feedId: number,
    sourceCreateSchema: SourceCreateSchema,
 ) => {
      return axiosInstance<SourceSchema>(
      {url: `/api/feeds/${feedId}/sources`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sourceCreateSchema
    },
      );
    }
  
/**
 * 소스 업데이트
 * @summary Update Source
 */
export const updateFeedSource = (
    feedId: number,
    sourceId: number,
    sourceUpdateSchema: SourceUpdateSchema,
 ) => {
      return axiosInstance<SourceSchema>(
      {url: `/api/feeds/${feedId}/sources/${sourceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: sourceUpdateSchema
    },
      );
    }
  
/**
 * 소스 삭제
 * @summary Delete Source
 */
export const deleteFeedSource = (
    feedId: number,
    sourceId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/sources/${sourceId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * 카테고리 목록 + 피드 목록 조회 (초기 로딩 최적화)
 * @summary List Categories With Feeds
 */
export const listCategoriesWithFeeds = (
    
 ) => {
      return axiosInstance<CategoryWithFeedsSchema[]>(
      {url: `/api/categories/with-feeds`, method: 'GET'
    },
      );
    }
  
/**
 * 카테고리 목록 조회
 * @summary List Categories
 */
export const listCategories = (
    
 ) => {
      return axiosInstance<CategorySchema[]>(
      {url: `/api/categories`, method: 'GET'
    },
      );
    }
  
/**
 * 카테고리 생성
 * @summary Create Category
 */
export const createCategory = (
    categoryCreateSchema: CategoryCreateSchema,
 ) => {
      return axiosInstance<CategorySchema>(
      {url: `/api/categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryCreateSchema
    },
      );
    }
  
/**
 * 카테고리 수정
 * @summary Update Category
 */
export const updateCategory = (
    categoryId: number,
    categoryUpdateSchema: CategoryUpdateSchema,
 ) => {
      return axiosInstance<CategorySchema>(
      {url: `/api/categories/${categoryId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryUpdateSchema
    },
      );
    }
  
/**
 * 카테고리 삭제
 * @summary Delete Category
 */
export const deleteCategory = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * 카테고리 순서 일괄 변경
 * @summary Reorder Categories
 */
export const reorderCategories = (
    categoryReorderSchema: CategoryReorderSchema,
 ) => {
      return axiosInstance<CategorySchema[]>(
      {url: `/api/categories/reorder`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryReorderSchema
    },
      );
    }
  
/**
 * 카테고리의 모든 피드 새로고침
 * @summary Refresh Category Feeds
 */
export const refreshCategoryFeeds = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}/refresh`, method: 'POST'
    },
      );
    }
  
/**
 * 카테고리 통계 조회
 * @summary Get Category Stats
 */
export const getCategoryStats = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}/stats`, method: 'GET'
    },
      );
    }
  
/**
 * 아이템 즐겨찾기 토글
 * @summary Toggle Item Favorite
 */
export const toggleItemFavorite = (
    itemId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/${itemId}/favorite`, method: 'PUT'
    },
      );
    }
  
/**
 * 아이템 읽음 상태 토글
 * @summary Toggle Item Read
 */
export const toggleItemRead = (
    itemId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/${itemId}/read`, method: 'PUT'
    },
      );
    }
  
/**
 * 메인 화면 아이템 목록
 * @summary List All Items
 */
export const listAllItems = (
    params?: ListAllItemsParams,
 ) => {
      return axiosInstance<PagedItemSchema>(
      {url: `/api/items`, method: 'GET',
        params
    },
      );
    }
  
/**
 * 카테고리별 아이템 목록
 * @summary List Items By Category
 */
export const listItemsByCategory = (
    categoryId: number,
    params?: ListItemsByCategoryParams,
 ) => {
      return axiosInstance<PagedItemSchema>(
      {url: `/api/items/category/${categoryId}`, method: 'GET',
        params
    },
      );
    }
  
/**
 * 피드별 아이템 목록
 * @summary List Items By Feed
 */
export const listItemsByFeed = (
    feedId: number,
    params?: ListItemsByFeedParams,
 ) => {
      return axiosInstance<PagedItemSchema>(
      {url: `/api/items/feed/${feedId}`, method: 'GET',
        params
    },
      );
    }
  
/**
 * 공개된 카테고리/피드의 아이템을 RSS/Atom 피드로 내보내기 (인증 불필요)
 * @summary Export All Items Rss
 */
export const exportAllItemsRss = (
    params?: ExportAllItemsRssParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/rss`, method: 'GET',
        params
    },
      );
    }
  
/**
 * 공개된 카테고리의 공개 피드 아이템을 RSS/Atom 피드로 내보내기 (인증 불필요)
 * @summary Export Category Items Rss
 */
export const exportCategoryItemsRss = (
    categoryId: number,
    params?: ExportCategoryItemsRssParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/category/${categoryId}/rss`, method: 'GET',
        params
    },
      );
    }
  
/**
 * 공개된 피드의 아이템을 RSS/Atom 피드로 내보내기 (인증 불필요)
 * @summary Export Feed Items Rss
 */
export const exportFeedItemsRss = (
    feedId: number,
    params?: ExportFeedItemsRssParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/feed/${feedId}/rss`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary Login
 */
export const usersRouterLogin = (
    loginRequest: LoginRequest,
 ) => {
      return axiosInstance<LoginResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  
/**
 * @summary Signup
 */
export const usersRouterSignup = (
    signupRequest: SignupRequest,
 ) => {
      return axiosInstance<SignupResponse>(
      {url: `/api/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest
    },
      );
    }
  
/**
 * @summary Protected
 */
export const usersRouterProtected = (
    
 ) => {
      return axiosInstance<ProtectedResponse>(
      {url: `/api/auth/protected`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Me
 */
export const usersRouterMe = (
    
 ) => {
      return axiosInstance<UserResponse>(
      {url: `/api/auth/me`, method: 'GET'
    },
      );
    }
  
/**
 * 글로벌 설정 조회 (관리자 전용)
 * @summary Get Global Settings
 */
export const usersRouterGetGlobalSettings = (
    
 ) => {
      return axiosInstance<GlobalSettingSchema>(
      {url: `/api/auth/admin/settings`, method: 'GET'
    },
      );
    }
  
/**
 * 글로벌 설정 업데이트 (관리자 전용)
 * @summary Update Global Settings
 */
export const usersRouterUpdateGlobalSettings = (
    globalSettingUpdateSchema: GlobalSettingUpdateSchema,
 ) => {
      return axiosInstance<GlobalSettingSchema>(
      {url: `/api/auth/admin/settings`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: globalSettingUpdateSchema
    },
      );
    }
  
/**
 * 회원가입 허용 여부 및 사이트 정보 확인 (공개 API)
 * @summary Get Signup Status
 */
export const usersRouterGetSignupStatus = (
    
 ) => {
      return axiosInstance<SignupStatusSchema>(
      {url: `/api/auth/signup-status`, method: 'GET'
    },
      );
    }
  
/**
 * URL에서 HTML을 가져옴
 * @summary Fetch Html
 */
export const fetchHtml = (
    fetchHTMLRequest: FetchHTMLRequest,
 ) => {
      return axiosInstance<FetchHTMLResponse>(
      {url: `/api/rss-everything/fetch-html`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fetchHTMLRequest
    },
      );
    }
  
/**
 * HTML에서 CSS 셀렉터로 요소들을 추출
 * @summary Extract Elements
 */
export const extractElements = (
    extractElementsRequest: ExtractElementsRequest,
 ) => {
      return axiosInstance<ExtractElementsResponse>(
      {url: `/api/rss-everything/extract-elements`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: extractElementsRequest
    },
      );
    }
  
/**
 * 설정된 셀렉터로 아이템들을 미리보기
 * @summary Preview Items
 */
export const previewItems = (
    previewItemRequest: PreviewItemRequest,
 ) => {
      return axiosInstance<PreviewItemResponse>(
      {url: `/api/rss-everything/preview-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: previewItemRequest
    },
      );
    }
  
/**
 * 사용자의 RSSEverything 소스 목록 조회
 * @summary List Sources
 */
export const listRssEverythingSources = (
    
 ) => {
      return axiosInstance<RSSEverythingSchema[]>(
      {url: `/api/rss-everything`, method: 'GET'
    },
      );
    }
  
/**
 * 기존 피드에 새 RSSEverything 소스 추가
 * @summary Create Source
 */
export const createRssEverythingSource = (
    rSSEverythingCreateRequest: RSSEverythingCreateRequest,
 ) => {
      return axiosInstance<RSSEverythingSchema>(
      {url: `/api/rss-everything`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rSSEverythingCreateRequest
    },
      );
    }
  
/**
 * RSSEverything 소스 상세 조회
 * @summary Get Source
 */
export const getRssEverythingSource = (
    sourceId: number,
 ) => {
      return axiosInstance<RSSEverythingSchema>(
      {url: `/api/rss-everything/${sourceId}`, method: 'GET'
    },
      );
    }
  
/**
 * RSSEverything 소스 수정
 * @summary Update Source Rss
 */
export const updateRssEverythingSource = (
    sourceId: number,
    rSSEverythingUpdateRequest: RSSEverythingUpdateRequest,
 ) => {
      return axiosInstance<RSSEverythingSchema>(
      {url: `/api/rss-everything/${sourceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: rSSEverythingUpdateRequest
    },
      );
    }
  
/**
 * RSSEverything 소스 삭제 - 연결된 RSSFeed도 함께 삭제
 * @summary Delete Source Rss
 */
export const deleteRssEverythingSource = (
    sourceId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/rss-everything/${sourceId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * RSSEverything 소스를 새로고침
 * @summary Refresh Source
 */
export const refreshRssEverythingSource = (
    sourceId: number,
 ) => {
      return axiosInstance<RefreshResponse>(
      {url: `/api/rss-everything/${sourceId}/refresh`, method: 'POST'
    },
      );
    }
  
/**
 * Task 결과 목록 조회
 * @summary List Task Results
 */
export const listTaskResults = (
    params?: ListTaskResultsParams,
 ) => {
      return axiosInstance<PagedTaskResultSchema>(
      {url: `/api/task-results`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Task 결과 일괄 삭제
 * @summary Clear Task Results
 */
export const clearTaskResults = (
    params?: ClearTaskResultsParams,
 ) => {
      return axiosInstance<void>(
      {url: `/api/task-results`, method: 'DELETE',
        params
    },
      );
    }
  
/**
 * Task 통계 조회
 * @summary Get Task Stats
 */
export const getTaskStats = (
    params?: GetTaskStatsParams,
 ) => {
      return axiosInstance<TaskStatsSchema>(
      {url: `/api/task-results/stats`, method: 'GET',
        params
    },
      );
    }
  
/**
 * 특정 Task 결과 상세 조회
 * @summary Get Task Result
 */
export const getTaskResult = (
    resultId: number,
 ) => {
      return axiosInstance<TaskResultSchema>(
      {url: `/api/task-results/${resultId}`, method: 'GET'
    },
      );
    }
  
/**
 * 특정 Task 결과 삭제
 * @summary Delete Task Result
 */
export const deleteTaskResult = (
    resultId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/task-results/${resultId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * 주기적 태스크 목록 조회
 * @summary List Periodic Tasks
 */
export const listPeriodicTasks = (
    params?: ListPeriodicTasksParams,
 ) => {
      return axiosInstance<PeriodicTaskListResponse>(
      {url: `/api/periodic-tasks`, method: 'GET',
        params
    },
      );
    }
  
/**
 * 주기적 태스크 통계 조회
 * @summary Get Periodic Task Stats
 */
export const getPeriodicTaskStats = (
    
 ) => {
      return axiosInstance<void>(
      {url: `/api/periodic-tasks/stats`, method: 'GET'
    },
      );
    }
  
/**
 * 특정 주기적 태스크 상세 조회
 * @summary Get Periodic Task
 */
export const getPeriodicTask = (
    taskId: number,
 ) => {
      return axiosInstance<PeriodicTaskSchema>(
      {url: `/api/periodic-tasks/${taskId}`, method: 'GET'
    },
      );
    }
  
/**
 * 주기적 태스크 업데이트
 * @summary Update Periodic Task
 */
export const updatePeriodicTask = (
    taskId: number,
    periodicTaskUpdateSchema: PeriodicTaskUpdateSchema,
 ) => {
      return axiosInstance<PeriodicTaskSchema>(
      {url: `/api/periodic-tasks/${taskId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: periodicTaskUpdateSchema
    },
      );
    }
  
/**
 * 주기적 태스크 삭제
 * @summary Delete Periodic Task
 */
export const deletePeriodicTask = (
    taskId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/periodic-tasks/${taskId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * 주기적 태스크 활성화/비활성화 토글
 * @summary Toggle Periodic Task
 */
export const togglePeriodicTask = (
    taskId: number,
 ) => {
      return axiosInstance<PeriodicTaskSchema>(
      {url: `/api/periodic-tasks/${taskId}/toggle`, method: 'POST'
    },
      );
    }
  
export type BaseApiHealthCheckResult = NonNullable<Awaited<ReturnType<typeof baseApiHealthCheck>>>
export type ValidateFeedResult = NonNullable<Awaited<ReturnType<typeof validateFeed>>>
export type ListFeedsResult = NonNullable<Awaited<ReturnType<typeof listFeeds>>>
export type CreateFeedResult = NonNullable<Awaited<ReturnType<typeof createFeed>>>
export type UpdateFeedResult = NonNullable<Awaited<ReturnType<typeof updateFeed>>>
export type DeleteFeedResult = NonNullable<Awaited<ReturnType<typeof deleteFeed>>>
export type RefreshFeedResult = NonNullable<Awaited<ReturnType<typeof refreshFeed>>>
export type MarkAllFeedItemsReadResult = NonNullable<Awaited<ReturnType<typeof markAllFeedItemsRead>>>
export type DeleteAllFeedItemsResult = NonNullable<Awaited<ReturnType<typeof deleteAllFeedItems>>>
export type AddFeedSourceResult = NonNullable<Awaited<ReturnType<typeof addFeedSource>>>
export type UpdateFeedSourceResult = NonNullable<Awaited<ReturnType<typeof updateFeedSource>>>
export type DeleteFeedSourceResult = NonNullable<Awaited<ReturnType<typeof deleteFeedSource>>>
export type ListCategoriesWithFeedsResult = NonNullable<Awaited<ReturnType<typeof listCategoriesWithFeeds>>>
export type ListCategoriesResult = NonNullable<Awaited<ReturnType<typeof listCategories>>>
export type CreateCategoryResult = NonNullable<Awaited<ReturnType<typeof createCategory>>>
export type UpdateCategoryResult = NonNullable<Awaited<ReturnType<typeof updateCategory>>>
export type DeleteCategoryResult = NonNullable<Awaited<ReturnType<typeof deleteCategory>>>
export type ReorderCategoriesResult = NonNullable<Awaited<ReturnType<typeof reorderCategories>>>
export type RefreshCategoryFeedsResult = NonNullable<Awaited<ReturnType<typeof refreshCategoryFeeds>>>
export type GetCategoryStatsResult = NonNullable<Awaited<ReturnType<typeof getCategoryStats>>>
export type ToggleItemFavoriteResult = NonNullable<Awaited<ReturnType<typeof toggleItemFavorite>>>
export type ToggleItemReadResult = NonNullable<Awaited<ReturnType<typeof toggleItemRead>>>
export type ListAllItemsResult = NonNullable<Awaited<ReturnType<typeof listAllItems>>>
export type ListItemsByCategoryResult = NonNullable<Awaited<ReturnType<typeof listItemsByCategory>>>
export type ListItemsByFeedResult = NonNullable<Awaited<ReturnType<typeof listItemsByFeed>>>
export type ExportAllItemsRssResult = NonNullable<Awaited<ReturnType<typeof exportAllItemsRss>>>
export type ExportCategoryItemsRssResult = NonNullable<Awaited<ReturnType<typeof exportCategoryItemsRss>>>
export type ExportFeedItemsRssResult = NonNullable<Awaited<ReturnType<typeof exportFeedItemsRss>>>
export type UsersRouterLoginResult = NonNullable<Awaited<ReturnType<typeof usersRouterLogin>>>
export type UsersRouterSignupResult = NonNullable<Awaited<ReturnType<typeof usersRouterSignup>>>
export type UsersRouterProtectedResult = NonNullable<Awaited<ReturnType<typeof usersRouterProtected>>>
export type UsersRouterMeResult = NonNullable<Awaited<ReturnType<typeof usersRouterMe>>>
export type UsersRouterGetGlobalSettingsResult = NonNullable<Awaited<ReturnType<typeof usersRouterGetGlobalSettings>>>
export type UsersRouterUpdateGlobalSettingsResult = NonNullable<Awaited<ReturnType<typeof usersRouterUpdateGlobalSettings>>>
export type UsersRouterGetSignupStatusResult = NonNullable<Awaited<ReturnType<typeof usersRouterGetSignupStatus>>>
export type FetchHtmlResult = NonNullable<Awaited<ReturnType<typeof fetchHtml>>>
export type ExtractElementsResult = NonNullable<Awaited<ReturnType<typeof extractElements>>>
export type PreviewItemsResult = NonNullable<Awaited<ReturnType<typeof previewItems>>>
export type ListRssEverythingSourcesResult = NonNullable<Awaited<ReturnType<typeof listRssEverythingSources>>>
export type CreateRssEverythingSourceResult = NonNullable<Awaited<ReturnType<typeof createRssEverythingSource>>>
export type GetRssEverythingSourceResult = NonNullable<Awaited<ReturnType<typeof getRssEverythingSource>>>
export type UpdateRssEverythingSourceResult = NonNullable<Awaited<ReturnType<typeof updateRssEverythingSource>>>
export type DeleteRssEverythingSourceResult = NonNullable<Awaited<ReturnType<typeof deleteRssEverythingSource>>>
export type RefreshRssEverythingSourceResult = NonNullable<Awaited<ReturnType<typeof refreshRssEverythingSource>>>
export type ListTaskResultsResult = NonNullable<Awaited<ReturnType<typeof listTaskResults>>>
export type ClearTaskResultsResult = NonNullable<Awaited<ReturnType<typeof clearTaskResults>>>
export type GetTaskStatsResult = NonNullable<Awaited<ReturnType<typeof getTaskStats>>>
export type GetTaskResultResult = NonNullable<Awaited<ReturnType<typeof getTaskResult>>>
export type DeleteTaskResultResult = NonNullable<Awaited<ReturnType<typeof deleteTaskResult>>>
export type ListPeriodicTasksResult = NonNullable<Awaited<ReturnType<typeof listPeriodicTasks>>>
export type GetPeriodicTaskStatsResult = NonNullable<Awaited<ReturnType<typeof getPeriodicTaskStats>>>
export type GetPeriodicTaskResult = NonNullable<Awaited<ReturnType<typeof getPeriodicTask>>>
export type UpdatePeriodicTaskResult = NonNullable<Awaited<ReturnType<typeof updatePeriodicTask>>>
export type DeletePeriodicTaskResult = NonNullable<Awaited<ReturnType<typeof deletePeriodicTask>>>
export type TogglePeriodicTaskResult = NonNullable<Awaited<ReturnType<typeof togglePeriodicTask>>>
