/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from '../utils/axiosInstance';
export type FeedValidationResponseLatestItemDate = string | null;

export interface FeedValidationResponse {
  title: string;
  description: string;
  items_count: number;
  latest_item_date?: FeedValidationResponseLatestItemDate;
}

export type FeedValidationRequestCustomHeaders = { [key: string]: unknown };

export interface FeedValidationRequest {
  url: string;
  custom_headers?: FeedValidationRequestCustomHeaders;
}

export type FeedSchemaCustomHeaders = { [key: string]: unknown };

export interface FeedSchema {
  id: number;
  category_id: number;
  url: string;
  title: string;
  favicon_url?: string;
  description: string;
  visible: boolean;
  custom_headers?: FeedSchemaCustomHeaders;
  refresh_interval?: number;
  last_updated: string;
  item_count: number;
}

export type FeedCreateSchemaCustomHeaders = { [key: string]: unknown };

export interface FeedCreateSchema {
  category_id: number;
  url: string;
  title?: string;
  description?: string;
  visible?: boolean;
  custom_headers?: FeedCreateSchemaCustomHeaders;
  refresh_interval?: number;
}

export type FeedUpdateSchemaCategoryId = number | null;

export type FeedUpdateSchemaUrl = string | null;

export type FeedUpdateSchemaTitle = string | null;

export type FeedUpdateSchemaFaviconUrl = string | null;

export type FeedUpdateSchemaDescription = string | null;

export type FeedUpdateSchemaVisible = boolean | null;

export type FeedUpdateSchemaCustomHeadersAnyOf = { [key: string]: unknown };

export type FeedUpdateSchemaCustomHeaders = FeedUpdateSchemaCustomHeadersAnyOf | null;

export type FeedUpdateSchemaRefreshInterval = number | null;

export interface FeedUpdateSchema {
  category_id?: FeedUpdateSchemaCategoryId;
  url?: FeedUpdateSchemaUrl;
  title?: FeedUpdateSchemaTitle;
  favicon_url?: FeedUpdateSchemaFaviconUrl;
  description?: FeedUpdateSchemaDescription;
  visible?: FeedUpdateSchemaVisible;
  custom_headers?: FeedUpdateSchemaCustomHeaders;
  refresh_interval?: FeedUpdateSchemaRefreshInterval;
}

export interface CategorySchema {
  id: number;
  name: string;
  description: string;
  visible: boolean;
  order: number;
}

export interface CategoryCreateSchema {
  name: string;
  description?: string;
  visible?: boolean;
}

export type CategoryUpdateSchemaName = string | null;

export type CategoryUpdateSchemaDescription = string | null;

export type CategoryUpdateSchemaVisible = boolean | null;

export type CategoryUpdateSchemaOrder = number | null;

export interface CategoryUpdateSchema {
  name?: CategoryUpdateSchemaName;
  description?: CategoryUpdateSchemaDescription;
  visible?: CategoryUpdateSchemaVisible;
  order?: CategoryUpdateSchemaOrder;
}

export interface CategoryReorderSchema {
  category_ids: number[];
}

export interface ItemSchema {
  id: number;
  feed_id: number;
  title: string;
  link: string;
  description: string;
  published_at: string;
  is_read: boolean;
  is_favorite: boolean;
}

export type PaginatedResponseItemSchemaNextCursor = string | null;

export interface PaginatedResponseItemSchema {
  items: ItemSchema[];
  has_next: boolean;
  next_cursor?: PaginatedResponseItemSchemaNextCursor;
}

export interface LoginResponse {
  token: string;
  user: UserResponse;
}

export interface UserResponse {
  id: number;
  username: string;
  email: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface SignupResponse {
  token: string;
  user: UserResponse;
}

export interface SignupRequest {
  username: string;
  password: string;
  email: string;
}

export interface ProtectedResponse {
  message: string;
}

export type FetchHTMLResponseHtml = string | null;

export type FetchHTMLResponseError = string | null;

/**
 * HTML 가져오기 응답
 */
export interface FetchHTMLResponse {
  success: boolean;
  html?: FetchHTMLResponseHtml;
  url: string;
  error?: FetchHTMLResponseError;
}

export type FetchHTMLRequestCustomHeaders = { [key: string]: unknown };

/**
 * HTML 가져오기 요청
 */
export interface FetchHTMLRequest {
  url: string;
  use_browser?: boolean;
  wait_selector?: string;
  timeout?: number;
  custom_headers?: FetchHTMLRequestCustomHeaders;
}

export type ElementInfoHref = string | null;

export type ElementInfoSrc = string | null;

/**
 * 추출된 요소 정보
 */
export interface ElementInfo {
  tag: string;
  text: string;
  html: string;
  href?: ElementInfoHref;
  src?: ElementInfoSrc;
  selector: string;
}

export type ExtractElementsResponseError = string | null;

/**
 * 요소 추출 응답
 */
export interface ExtractElementsResponse {
  success: boolean;
  elements?: ElementInfo[];
  count?: number;
  error?: ExtractElementsResponseError;
}

/**
 * 요소 추출 요청
 */
export interface ExtractElementsRequest {
  html: string;
  selector: string;
  base_url: string;
}

/**
 * 미리보기 아이템
 */
export interface PreviewItem {
  title: string;
  link: string;
  description?: string;
  date?: string;
  image?: string;
}

export type PreviewItemResponseError = string | null;

/**
 * 아이템 미리보기 응답
 */
export interface PreviewItemResponse {
  success: boolean;
  items?: PreviewItem[];
  count?: number;
  error?: PreviewItemResponseError;
}

export type PreviewItemRequestCustomHeaders = { [key: string]: unknown };

/**
 * 아이템 미리보기 요청 - 선택한 셀렉터로 아이템 추출 테스트
 */
export interface PreviewItemRequest {
  url: string;
  item_selector: string;
  title_selector?: string;
  link_selector?: string;
  description_selector?: string;
  date_selector?: string;
  image_selector?: string;
  use_browser?: boolean;
  wait_selector?: string;
  custom_headers?: PreviewItemRequestCustomHeaders;
  exclude_selectors?: string[];
  follow_links?: boolean;
  detail_title_selector?: string;
  detail_description_selector?: string;
  detail_content_selector?: string;
  detail_date_selector?: string;
  detail_image_selector?: string;
}

export type RSSEverythingSchemaLastCrawledAt = string | null;

/**
 * RSSEverything 소스 스키마
 */
export interface RSSEverythingSchema {
  id: number;
  feed_id: number;
  url: string;
  item_selector: string;
  title_selector: string;
  link_selector: string;
  description_selector: string;
  date_selector: string;
  image_selector: string;
  follow_links: boolean;
  detail_title_selector: string;
  detail_description_selector: string;
  detail_content_selector: string;
  detail_date_selector: string;
  detail_image_selector: string;
  exclude_selectors: string[];
  date_formats: string[];
  date_locale: string;
  use_browser: boolean;
  wait_selector: string;
  timeout: number;
  last_crawled_at: RSSEverythingSchemaLastCrawledAt;
  last_error: string;
  created_at: string;
  updated_at: string;
}

export type RSSEverythingCreateRequestCustomHeaders = { [key: string]: unknown };

/**
 * RSSEverything 소스 생성 요청
 */
export interface RSSEverythingCreateRequest {
  name: string;
  url: string;
  category_id: number;
  refresh_interval?: number;
  custom_headers?: RSSEverythingCreateRequestCustomHeaders;
  item_selector: string;
  title_selector?: string;
  link_selector?: string;
  description_selector?: string;
  date_selector?: string;
  image_selector?: string;
  follow_links?: boolean;
  detail_title_selector?: string;
  detail_description_selector?: string;
  detail_content_selector?: string;
  detail_date_selector?: string;
  detail_image_selector?: string;
  exclude_selectors?: string[];
  date_formats?: string[];
  date_locale?: string;
  use_browser?: boolean;
  wait_selector?: string;
  timeout?: number;
}

export type RSSEverythingUpdateRequestItemSelector = string | null;

export type RSSEverythingUpdateRequestTitleSelector = string | null;

export type RSSEverythingUpdateRequestLinkSelector = string | null;

export type RSSEverythingUpdateRequestDescriptionSelector = string | null;

export type RSSEverythingUpdateRequestDateSelector = string | null;

export type RSSEverythingUpdateRequestImageSelector = string | null;

export type RSSEverythingUpdateRequestFollowLinks = boolean | null;

export type RSSEverythingUpdateRequestDetailTitleSelector = string | null;

export type RSSEverythingUpdateRequestDetailDescriptionSelector = string | null;

export type RSSEverythingUpdateRequestDetailContentSelector = string | null;

export type RSSEverythingUpdateRequestDetailDateSelector = string | null;

export type RSSEverythingUpdateRequestDetailImageSelector = string | null;

export type RSSEverythingUpdateRequestExcludeSelectors = string[] | null;

export type RSSEverythingUpdateRequestDateFormats = string[] | null;

export type RSSEverythingUpdateRequestDateLocale = string | null;

export type RSSEverythingUpdateRequestUseBrowser = boolean | null;

export type RSSEverythingUpdateRequestWaitSelector = string | null;

export type RSSEverythingUpdateRequestTimeout = number | null;

/**
 * RSSEverything 소스 수정 요청
 */
export interface RSSEverythingUpdateRequest {
  item_selector?: RSSEverythingUpdateRequestItemSelector;
  title_selector?: RSSEverythingUpdateRequestTitleSelector;
  link_selector?: RSSEverythingUpdateRequestLinkSelector;
  description_selector?: RSSEverythingUpdateRequestDescriptionSelector;
  date_selector?: RSSEverythingUpdateRequestDateSelector;
  image_selector?: RSSEverythingUpdateRequestImageSelector;
  follow_links?: RSSEverythingUpdateRequestFollowLinks;
  detail_title_selector?: RSSEverythingUpdateRequestDetailTitleSelector;
  detail_description_selector?: RSSEverythingUpdateRequestDetailDescriptionSelector;
  detail_content_selector?: RSSEverythingUpdateRequestDetailContentSelector;
  detail_date_selector?: RSSEverythingUpdateRequestDetailDateSelector;
  detail_image_selector?: RSSEverythingUpdateRequestDetailImageSelector;
  exclude_selectors?: RSSEverythingUpdateRequestExcludeSelectors;
  date_formats?: RSSEverythingUpdateRequestDateFormats;
  date_locale?: RSSEverythingUpdateRequestDateLocale;
  use_browser?: RSSEverythingUpdateRequestUseBrowser;
  wait_selector?: RSSEverythingUpdateRequestWaitSelector;
  timeout?: RSSEverythingUpdateRequestTimeout;
}

export type FeedsRoutersItemListAllItemsParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
limit?: number;
cursor?: string | null;
direction?: string;
};

export type FeedsRoutersItemListItemsByCategoryParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
limit?: number;
cursor?: string | null;
direction?: string;
};

export type FeedsRoutersItemListItemsByFeedParams = {
is_read?: boolean | null;
is_favorite?: boolean | null;
search?: string;
limit?: number;
cursor?: string | null;
direction?: string;
};

/**
 * @summary Health Check
 */
export const baseApiHealthCheck = (
    
 ) => {
      return axiosInstance<void>(
      {url: `/api/health`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Validate Feed
 */
export const feedsRoutersFeedValidateFeed = (
    feedValidationRequest: FeedValidationRequest,
 ) => {
      return axiosInstance<FeedValidationResponse>(
      {url: `/api/feeds/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feedValidationRequest
    },
      );
    }
  
/**
 * @summary List Feeds
 */
export const feedsRoutersFeedListFeeds = (
    
 ) => {
      return axiosInstance<FeedSchema[]>(
      {url: `/api/feeds`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create Feed
 */
export const feedsRoutersFeedCreateFeed = (
    feedCreateSchema: FeedCreateSchema,
 ) => {
      return axiosInstance<FeedSchema>(
      {url: `/api/feeds`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: feedCreateSchema
    },
      );
    }
  
/**
 * @summary Update Feed
 */
export const feedsRoutersFeedUpdateFeed = (
    feedId: number,
    feedUpdateSchema: FeedUpdateSchema,
 ) => {
      return axiosInstance<FeedSchema>(
      {url: `/api/feeds/${feedId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: feedUpdateSchema
    },
      );
    }
  
/**
 * @summary Delete Feed
 */
export const feedsRoutersFeedDeleteFeed = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Refresh Feed
 */
export const feedsRoutersFeedRefreshFeed = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/refresh`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Mark All Feed Items Read
 */
export const feedsRoutersFeedMarkAllFeedItemsRead = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/mark-all-read`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary Delete All Feed Items
 */
export const feedsRoutersFeedDeleteAllFeedItems = (
    feedId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/feeds/${feedId}/items`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary List Categories
 */
export const feedsRoutersCategoryListCategories = (
    
 ) => {
      return axiosInstance<CategorySchema[]>(
      {url: `/api/categories`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Create Category
 */
export const feedsRoutersCategoryCreateCategory = (
    categoryCreateSchema: CategoryCreateSchema,
 ) => {
      return axiosInstance<CategorySchema>(
      {url: `/api/categories`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryCreateSchema
    },
      );
    }
  
/**
 * @summary Update Category
 */
export const feedsRoutersCategoryUpdateCategory = (
    categoryId: number,
    categoryUpdateSchema: CategoryUpdateSchema,
 ) => {
      return axiosInstance<CategorySchema>(
      {url: `/api/categories/${categoryId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: categoryUpdateSchema
    },
      );
    }
  
/**
 * @summary Delete Category
 */
export const feedsRoutersCategoryDeleteCategory = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * 카테고리 순서 일괄 변경
 * @summary Reorder Categories
 */
export const feedsRoutersCategoryReorderCategories = (
    categoryReorderSchema: CategoryReorderSchema,
 ) => {
      return axiosInstance<CategorySchema[]>(
      {url: `/api/categories/reorder`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoryReorderSchema
    },
      );
    }
  
/**
 * @summary Refresh Category Feeds
 */
export const feedsRoutersCategoryRefreshCategoryFeeds = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}/refresh`, method: 'POST'
    },
      );
    }
  
/**
 * @summary Get Category Stats
 */
export const feedsRoutersCategoryGetCategoryStats = (
    categoryId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/categories/${categoryId}/stats`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Toggle Item Favorite
 */
export const feedsRoutersItemToggleItemFavorite = (
    itemId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/${itemId}/favorite`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary Toggle Item Read
 */
export const feedsRoutersItemToggleItemRead = (
    itemId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/items/${itemId}/read`, method: 'PUT'
    },
      );
    }
  
/**
 * @summary List All Items
 */
export const feedsRoutersItemListAllItems = (
    params?: FeedsRoutersItemListAllItemsParams,
 ) => {
      return axiosInstance<PaginatedResponseItemSchema>(
      {url: `/api/items`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary List Items By Category
 */
export const feedsRoutersItemListItemsByCategory = (
    categoryId: number,
    params?: FeedsRoutersItemListItemsByCategoryParams,
 ) => {
      return axiosInstance<PaginatedResponseItemSchema>(
      {url: `/api/items/category/${categoryId}`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary List Items By Feed
 */
export const feedsRoutersItemListItemsByFeed = (
    feedId: number,
    params?: FeedsRoutersItemListItemsByFeedParams,
 ) => {
      return axiosInstance<PaginatedResponseItemSchema>(
      {url: `/api/items/feed/${feedId}`, method: 'GET',
        params
    },
      );
    }
  
/**
 * @summary Login
 */
export const usersRouterLogin = (
    loginRequest: LoginRequest,
 ) => {
      return axiosInstance<LoginResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  
/**
 * @summary Signup
 */
export const usersRouterSignup = (
    signupRequest: SignupRequest,
 ) => {
      return axiosInstance<SignupResponse>(
      {url: `/api/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest
    },
      );
    }
  
/**
 * @summary Protected
 */
export const usersRouterProtected = (
    
 ) => {
      return axiosInstance<ProtectedResponse>(
      {url: `/api/auth/protected`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Me
 */
export const usersRouterMe = (
    
 ) => {
      return axiosInstance<UserResponse>(
      {url: `/api/auth/me`, method: 'GET'
    },
      );
    }
  
/**
 * URL에서 HTML을 가져옵니다.
브라우저 렌더링을 사용하여 JavaScript로 생성된 콘텐츠도 가져올 수 있습니다.
 * @summary Fetch Html
 */
export const feedsRoutersRssEverythingFetchHtml = (
    fetchHTMLRequest: FetchHTMLRequest,
 ) => {
      return axiosInstance<FetchHTMLResponse>(
      {url: `/api/rss-everything/fetch-html`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: fetchHTMLRequest
    },
      );
    }
  
/**
 * HTML에서 CSS 셀렉터로 요소들을 추출합니다.
프론트엔드에서 사용자가 선택한 요소의 정보를 확인하는 데 사용됩니다.
 * @summary Extract Elements
 */
export const feedsRoutersRssEverythingExtractElements = (
    extractElementsRequest: ExtractElementsRequest,
 ) => {
      return axiosInstance<ExtractElementsResponse>(
      {url: `/api/rss-everything/extract-elements`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: extractElementsRequest
    },
      );
    }
  
/**
 * 설정된 셀렉터로 아이템들을 미리보기합니다.
실제 저장하기 전에 셀렉터가 올바르게 작동하는지 확인할 수 있습니다.

follow_links=True인 경우:
- 목록 페이지에서 링크 수집
- 각 상세 페이지에서 detail_*_selector로 내용 추출
 * @summary Preview Items
 */
export const feedsRoutersRssEverythingPreviewItems = (
    previewItemRequest: PreviewItemRequest,
 ) => {
      return axiosInstance<PreviewItemResponse>(
      {url: `/api/rss-everything/preview-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: previewItemRequest
    },
      );
    }
  
/**
 * 사용자의 RSSEverything 소스 목록 조회
 * @summary List Sources
 */
export const feedsRoutersRssEverythingListSources = (
    
 ) => {
      return axiosInstance<RSSEverythingSchema[]>(
      {url: `/api/rss-everything`, method: 'GET'
    },
      );
    }
  
/**
 * 새 RSSEverything 소스 생성
RSSFeed를 먼저 생성하고, RSSEverythingSource를 연결합니다.
 * @summary Create Source
 */
export const feedsRoutersRssEverythingCreateSource = (
    rSSEverythingCreateRequest: RSSEverythingCreateRequest,
 ) => {
      return axiosInstance<RSSEverythingSchema>(
      {url: `/api/rss-everything`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rSSEverythingCreateRequest
    },
      );
    }
  
/**
 * RSSEverything 소스 상세 조회
 * @summary Get Source
 */
export const feedsRoutersRssEverythingGetSource = (
    sourceId: number,
 ) => {
      return axiosInstance<RSSEverythingSchema>(
      {url: `/api/rss-everything/${sourceId}`, method: 'GET'
    },
      );
    }
  
/**
 * RSSEverything 소스 수정
 * @summary Update Source
 */
export const feedsRoutersRssEverythingUpdateSource = (
    sourceId: number,
    rSSEverythingUpdateRequest: RSSEverythingUpdateRequest,
 ) => {
      return axiosInstance<RSSEverythingSchema>(
      {url: `/api/rss-everything/${sourceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: rSSEverythingUpdateRequest
    },
      );
    }
  
/**
 * RSSEverything 소스 삭제 - 연결된 RSSFeed도 함께 삭제됩니다.
 * @summary Delete Source
 */
export const feedsRoutersRssEverythingDeleteSource = (
    sourceId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/api/rss-everything/${sourceId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * RSSEverything 소스를 새로고침하여 아이템들을 업데이트합니다.
 * @summary Refresh Source
 */
export const feedsRoutersRssEverythingRefreshSource = (
    sourceId: number,
 ) => {
      return axiosInstance<RSSEverythingSchema>(
      {url: `/api/rss-everything/${sourceId}/refresh`, method: 'POST'
    },
      );
    }

// ============== Task Results API ==============

/**
 * 피드 기본 정보
 */
export interface TaskResultFeedInfo {
  id: number;
  title: string;
  url: string;
}

export type TaskResultStatus = 'pending' | 'running' | 'success' | 'failure';

/**
 * Task 결과 스키마
 */
export interface TaskResultSchema {
  id: number;
  feed: TaskResultFeedInfo;
  task_id: string;
  status: TaskResultStatus;
  items_found: number;
  items_created: number;
  error_message: string;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
  duration_seconds: number | null;
}

/**
 * Task 결과 목록 응답
 */
export interface TaskResultListResponse {
  items: TaskResultSchema[];
  total: number;
}

/**
 * Task 통계
 */
export interface TaskStatsSchema {
  total: number;
  success: number;
  failure: number;
  pending: number;
  running: number;
}

export type ListTaskResultsParams = {
  feed_id?: number;
  status?: TaskResultStatus;
  limit?: number;
  offset?: number;
};

/**
 * Task 결과 목록 조회
 * @summary List Task Results
 */
export const feedsRoutersTaskResultsListTaskResults = (
  params?: ListTaskResultsParams,
) => {
  return axiosInstance<TaskResultListResponse>({
    url: `/api/task-results`,
    method: 'GET',
    params,
  });
};

/**
 * Task 통계 조회
 * @summary Get Task Stats
 */
export const feedsRoutersTaskResultsGetTaskStats = (
  feedId?: number,
) => {
  return axiosInstance<TaskStatsSchema>({
    url: `/api/task-results/stats`,
    method: 'GET',
    params: feedId ? { feed_id: feedId } : undefined,
  });
};

/**
 * 특정 Task 결과 상세 조회
 * @summary Get Task Result
 */
export const feedsRoutersTaskResultsGetTaskResult = (
  resultId: number,
) => {
  return axiosInstance<TaskResultSchema>({
    url: `/api/task-results/${resultId}`,
    method: 'GET',
  });
};

/**
 * 특정 Task 결과 삭제
 * @summary Delete Task Result
 */
export const feedsRoutersTaskResultsDeleteTaskResult = (
  resultId: number,
) => {
  return axiosInstance<{ success: boolean }>({
    url: `/api/task-results/${resultId}`,
    method: 'DELETE',
  });
};

/**
 * Task 결과 일괄 삭제
 * @summary Clear Task Results
 */
export const feedsRoutersTaskResultsClearTaskResults = (
  params?: { feed_id?: number; status?: TaskResultStatus },
) => {
  return axiosInstance<{ success: boolean; deleted: number }>({
    url: `/api/task-results`,
    method: 'DELETE',
    params,
  });
};

export type BaseApiHealthCheckResult = NonNullable<Awaited<ReturnType<typeof baseApiHealthCheck>>>
export type FeedsRoutersFeedValidateFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedValidateFeed>>>
export type FeedsRoutersFeedListFeedsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedListFeeds>>>
export type FeedsRoutersFeedCreateFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedCreateFeed>>>
export type FeedsRoutersFeedUpdateFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedUpdateFeed>>>
export type FeedsRoutersFeedDeleteFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedDeleteFeed>>>
export type FeedsRoutersFeedRefreshFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedRefreshFeed>>>
export type FeedsRoutersFeedMarkAllFeedItemsReadResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedMarkAllFeedItemsRead>>>
export type FeedsRoutersFeedDeleteAllFeedItemsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersFeedDeleteAllFeedItems>>>
export type FeedsRoutersCategoryListCategoriesResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryListCategories>>>
export type FeedsRoutersCategoryCreateCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryCreateCategory>>>
export type FeedsRoutersCategoryUpdateCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryUpdateCategory>>>
export type FeedsRoutersCategoryDeleteCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryDeleteCategory>>>
export type FeedsRoutersCategoryReorderCategoriesResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryReorderCategories>>>
export type FeedsRoutersCategoryRefreshCategoryFeedsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryRefreshCategoryFeeds>>>
export type FeedsRoutersCategoryGetCategoryStatsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersCategoryGetCategoryStats>>>
export type FeedsRoutersItemToggleItemFavoriteResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemToggleItemFavorite>>>
export type FeedsRoutersItemToggleItemReadResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemToggleItemRead>>>
export type FeedsRoutersItemListAllItemsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemListAllItems>>>
export type FeedsRoutersItemListItemsByCategoryResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemListItemsByCategory>>>
export type FeedsRoutersItemListItemsByFeedResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersItemListItemsByFeed>>>
export type UsersRouterLoginResult = NonNullable<Awaited<ReturnType<typeof usersRouterLogin>>>
export type UsersRouterSignupResult = NonNullable<Awaited<ReturnType<typeof usersRouterSignup>>>
export type UsersRouterProtectedResult = NonNullable<Awaited<ReturnType<typeof usersRouterProtected>>>
export type UsersRouterMeResult = NonNullable<Awaited<ReturnType<typeof usersRouterMe>>>
export type FeedsRoutersRssEverythingFetchHtmlResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingFetchHtml>>>
export type FeedsRoutersRssEverythingExtractElementsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingExtractElements>>>
export type FeedsRoutersRssEverythingPreviewItemsResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingPreviewItems>>>
export type FeedsRoutersRssEverythingListSourcesResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingListSources>>>
export type FeedsRoutersRssEverythingCreateSourceResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingCreateSource>>>
export type FeedsRoutersRssEverythingGetSourceResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingGetSource>>>
export type FeedsRoutersRssEverythingUpdateSourceResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingUpdateSource>>>
export type FeedsRoutersRssEverythingDeleteSourceResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingDeleteSource>>>
export type FeedsRoutersRssEverythingRefreshSourceResult = NonNullable<Awaited<ReturnType<typeof feedsRoutersRssEverythingRefreshSource>>>
