# Generated by Django 5.2.9 on 2025-12-19 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsetting',
            options={'verbose_name': 'Global Setting', 'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='allow_signup',
            field=models.BooleanField(default=True, help_text='새로운 사용자의 회원가입 허용 여부'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='default_refresh_interval',
            field=models.IntegerField(default=60, help_text='기본 새로고침 간격 (분)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='max_feeds_per_user',
            field=models.IntegerField(default=100, help_text='사용자당 최대 피드 수', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='site_name',
            field=models.CharField(default='DRSS', help_text='사이트 이름', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='admin_signed',
            field=models.BooleanField(default=False, help_text='관리자가 가입했는지 여부'),
        ),
    ]
