# Generated by Django 5.2.9 on 2026-01-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_globalsetting_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsetting',
            name='admin_signed',
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='allow_signup',
            field=models.BooleanField(default=False, help_text='새로운 사용자의 회원가입 허용 여부'),
        ),
    ]
